-- create tables
-- copia de datos a la fecha 18/09/2023
-- usuario 1124
create table saf.con_indicadores_formulas_copy (
    id                             number generated by default on null as identity 
                                   constraint con_indicadores_fo_id_pk primary key,
    id_indicador                   number(10,0),
    cod_cta                        varchar2(20 char),
    codigo_gasto                   varchar2(20 char),
    funcion                        varchar2(1 char),
    usuario_grabacion              number(10,0),
    fecha_grabacion                date,
    usuario_modificacion           number(10,0),
    fecha_modificacion             date
)
;

grant all on CON_INDICADORES_FORMULAS to public;
create or replace public synonym CON_INDICADORES_FORMULAS for saf.CON_INDICADORES_FORMULAS;

-- load data
 
-- Generated by Quick SQL Monday September 18, 2023  10:57:52
 
/*
CON_INDICADORES_FORMULAS_COPY {
    ID,
    ID_INDICADOR NUM(10,0),
    COD_CTA VC20,
    CODIGO_GASTO VC20,
    FUNCION VC1,
    USUARIO_GRABACION NUM(10,0)
    FECHA_GRABACION DATE,
    USUARIO_MODIFICACION NUM(10,0),
    FECHA_MODIFICACION DATE
}

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
