CREATE OR REPLACE FORCE EDITIONABLE VIEW SAF."VW_CXP_PERIODO_PAGO_PROVEEDORES" ("CODIGO_EMPRESA", "CODIGO_DIVISION", "CODIGO_PROVEEDOR", "SERIE_DOCUMENTO", "NUMERO_DOCUMENTO", "NUMERO_OC", "CODIGO_GASTO", "FECHA_TRANSACCION", "FECHA_VENCIMIENTO", "FECHA_CANCELACION", "DIASVENCIDOS", "CODIGO_MONEDA", "TIPO_CAMBIO", "CARGO_ORIGEN", "CARGO_LOCAL", "TREINTA", "SESENTA", "MAXSESENTA") AS
(
SELECT
    A.CODIGO_EMPRESA,
    A.CODIGO_DIVISION,
    A.CODIGO_PROVEEDOR,
    A.SERIE_DOCUMENTO,
    A.NUMERO_DOCUMENTO,
    A.NUMERO_OC,
    A.CODIGO_GASTO,
    A.FECHA_TRANSACCION,
    A.FECHA_VENCIMIENTO,
    A.FECHA_CANCELACION,
    (
        SAF.FNC_GET_CXP_DIAS_VENCIDOS(A.FECHA_VENCIMIENTO)
    ) DIASVENCIDOS,
    A.CODIGO_MONEDA,
    A.TIPO_CAMBIO,
    A.CARGO_ORIGEN,
    A.CARGO_LOCAL,
    (
        CASE
            WHEN SAF.FNC_GET_CXP_DIAS_VENCIDOS(A.FECHA_VENCIMIENTO) > 0  AND SAF.FNC_GET_CXP_DIAS_VENCIDOS(A.FECHA_VENCIMIENTO) <= 30 THEN
                NVL(A.CARGO_LOCAL,0) - NVL(FNC_GET_CXPMONTORELACIONADO(A.CODIGO_EMPRESA, A.CODIGO_PROVEEDOR, A.TIPO_TRANSACCION, A.SERIE_DOCUMENTO, A.NUMERO_DOCUMENTO), 0)
            ELSE
                0
            END
        ) TREINTA,
    (
        CASE
            WHEN SAF.FNC_GET_CXP_DIAS_VENCIDOS(A.FECHA_VENCIMIENTO) > 30  AND SAF.FNC_GET_CXP_DIAS_VENCIDOS(A.FECHA_VENCIMIENTO) <= 60 THEN
                NVL(A.CARGO_LOCAL,0) - NVL(FNC_GET_CXPMONTORELACIONADO(A.CODIGO_EMPRESA, A.CODIGO_PROVEEDOR, A.TIPO_TRANSACCION, A.SERIE_DOCUMENTO, A.NUMERO_DOCUMENTO), 0)
            ELSE
                0
            END
        ) SESENTA,
    (
        CASE
            WHEN SAF.FNC_GET_CXP_DIAS_VENCIDOS(A.FECHA_VENCIMIENTO) > 60 THEN
                NVL(A.CARGO_LOCAL,0) - NVL(FNC_GET_CXPMONTORELACIONADO(A.CODIGO_EMPRESA, A.CODIGO_PROVEEDOR, A.TIPO_TRANSACCION, A.SERIE_DOCUMENTO, A.NUMERO_DOCUMENTO), 0)
            ELSE
                0
            END
        ) MAXSESENTA
FROM SAF.CXP_TRANSACCIONES A
LEFT JOIN CXP_COMPROMISOS_PAGO B
    ON A.TIPO_TRANSACCION = B.TIPO_TRANSACCION
    AND A.CODIGO_PROVEEDOR = B.CODIGO_PROVEEDOR
    AND A.SERIE_DOCUMENTO = B.SERIE_DOCUMENTO
    AND TO_CHAR(A.NUMERO_DOCUMENTO) = B.NUMERO_DOCUMENTO
LEFT JOIN CXP_CONTRASENA C
    ON B.NUMERO_CONTRASENA = C.NUMERO_CONTRASENA
INNER JOIN SAF.GRAL_EMPRESAS D
    ON D.CODIGO_EMPRESA = A.CODIGO_EMPRESA
INNER JOIN SAF.CXP_PROVEEDORES E
    ON A.CODIGO_PROVEEDOR = E.CODIGO_PROVEEDOR
WHERE A.CODIGO_EMPRESA > 99
AND A.CODIGO_PROVEEDOR > 0
AND A.TIPO_TRANSACCION IN
  (
      SELECT A.TIPO_TRANSACCION FROM SAF.GRAL_TIPOS_TRANSAC_MODULOS A WHERE A.CARGO_ABONO = 'C' AND A.CODIGO_MODULO = 12
  )
AND TO_CHAR(A.FECHA_TRANSACCION, 'YYYY') >= 2020
AND A.CODIGO_DIVISION IS NOT NULL
AND ABS(ROUND(NVL(A.CARGO_LOCAL,0) - NVL(FNC_GET_CXPMONTORELACIONADO(A.CODIGO_EMPRESA, A.CODIGO_PROVEEDOR, A.TIPO_TRANSACCION, A.SERIE_DOCUMENTO, A.NUMERO_DOCUMENTO), 0), 2)) > 0.05)