-- create tables
create table saf.ht_hoja_de_tiempos (
                                    id                             number generated by default on null as identity
                                        constraint ht_hoja_de_tiempos_id_pk primary key,
                                    fecha_inicio                   date,
                                    fecha_fin                      date,
                                    estado                         varchar2(100 char) default 'INVALIDO',
                                    tipo_vista                     number not null,
                                    usuario_grabacion              number not null,
                                    fecha_grabacion                date default SYSDATE
)
;

ALTER TABLE SAF.HT_HOJA_DE_TIEMPOS ADD CODIGO_EMPRESA NUMBER;
ALTER TABLE SAF.HT_HOJA_DE_TIEMPOS ADD CODIGO_DIVISION NUMBER;
ALTER TABLE SAF.HT_HOJA_DE_TIEMPOS ADD CODIGO_PROYECTO VARCHAR2(256);
ALTER TABLE SAF.HT_HOJA_DE_TIEMPOS ADD TIPO_PERIODO VARCHAR2(32);
ALTER TABLE SAF.HT_HOJA_DE_TIEMPOS ADD ANIO NUMBER;
ALTER TABLE SAF.HT_HOJA_DE_TIEMPOS ADD SERIE VARCHAR2(32);

create table saf.ht_tareas_administrativas (
                                           id                             number generated by default on null as identity
                                               constraint ht_tareas_administ_id_pk primary key,
                                           id_ht_hoja_de_tiempos          number
                                               constraint ht_tareas_adm_id_ht_hoja_de_fk
                                                   references ht_hoja_de_tiempos on delete cascade not null,
                                           id_padre                       number,
                                           titulo                         varchar2(1024 char) not null,
                                           tipo_registro                  varchar2(10 char) default 'R',
                                           fecha                          date not null,
                                           cantidad_horas                 number not null,
                                           estado                         varchar2(100 char) default 'INVALIDO',
                                           usuario_aprobador              number,
                                           usuario_grabacion              number not null,
                                           fecha_grabacion                date default SYSDATE,
                                           usuario_modificacion           number,
                                           fecha_modificacion             date
)
;
ALTER TABLE SAF.HT_TAREAS_ADMINISTRATIVAS ADD CODIGO_RENGLON VARCHAR2(1024);
ALTER TABLE SAF.HT_TAREAS_ADMINISTRATIVAS ADD CODIGO_RENGLON_PADRE VARCHAR2(1024);
ALTER TABLE SAF.HT_TAREAS_ADMINISTRATIVAS ADD ORDEN NUMBER;
ALTER TABLE SAF.HT_TAREAS_ADMINISTRATIVAS ADD ID_REGISTRO NUMBER;

-- table index
create index saf.ht_tareas_administ_i1 on saf.ht_tareas_administrativas (id_ht_hoja_de_tiempos);

create table saf.ht_renglones_servicos (
                                       id                             number generated by default on null as identity
                                           constraint ht_renglones_servi_id_pk primary key,
                                       id_ht_hoja_de_tiempos          number
                                           constraint ht_renglones_id_ht_hoja_de_fk
                                               references ht_hoja_de_tiempos on delete cascade not null,
                                       id_est_cs_renglones            number
                                           constraint ht_renglones_id_est_cs_ren_fk
                                               references est_cs_renglones on delete cascade,
                                       id_est_cs_contratos_servicio   number
                                           constraint ht_renglones_id_est_cs_con_fk
                                               references est_cs_contratos_servicio on delete cascade,
                                       id_padre                       number,
                                       titulo                         varchar2(1024 char) not null,
                                       tipo_registro                  varchar2(10 char) default 'CS',
                                       fecha                          date not null,
                                       cantidad_horas                 number not null,
                                       estado                         varchar2(100 char) default 'INVALIDO',
                                       usuario_aprobador              number,
                                       usuario_grabacion              number not null,
                                       fecha_grabacion                date default SYSDATE,
                                       usuario_modificacion           number,
                                       fecha_modificacion             date
)
;
ALTER TABLE SAF.HT_RENGLONES_SERVICOS ADD CODIGO_RENGLON VARCHAR2(1024);
ALTER TABLE SAF.HT_RENGLONES_SERVICOS ADD CODIGO_RENGLON_PADRE VARCHAR2(1024);
ALTER TABLE SAF.HT_RENGLONES_SERVICOS ADD ORDEN NUMBER;

-- table index
create index saf.ht_renglones_servi_i1 on saf.ht_renglones_servicos (id_est_cs_contratos_servicio);
create index saf.ht_renglones_servi_i92 on saf.ht_renglones_servicos (id_est_cs_renglones);
create index saf.ht_renglones_servi_i103 on saf.ht_renglones_servicos (id_ht_hoja_de_tiempos);

create table saf.ht_actividades_servicos (
                                         id                             number generated by default on null as identity
                                             constraint ht_actividades_ser_id_pk primary key,
                                         id_ht_hoja_de_tiempos          number
                                             constraint ht_actividade_id_ht_hoja_de_fk
                                                 references ht_hoja_de_tiempos on delete cascade not null,
                                         id_est_cs_actividades          number
                                             constraint ht_actividade_id_est_cs_act_fk
                                                 references est_cs_actividades on delete cascade,
                                         id_ht_renglones_servicos       number
                                             constraint ht_actividade_id_ht_renglon_fk
                                                 references ht_renglones_servicos on delete cascade,
                                         titulo                         varchar2(1024 char) not null,
                                         tipo_registro                  varchar2(10 char) default 'R',
                                         fecha                          date not null,
                                         cantidad_horas                 number not null,
                                         estado                         varchar2(100 char) default 'INVALIDO',
                                         usuario_aprobador              number,
                                         usuario_grabacion              number not null,
                                         fecha_grabacion                date default SYSDATE,
                                         usuario_modificacion           number,
                                         fecha_modificacion             date
)
;
ALTER TABLE SAF.HT_ACTIVIDADES_SERVICOS ADD CODIGO_RENGLON VARCHAR2(1024);
ALTER TABLE SAF.HT_ACTIVIDADES_SERVICOS ADD CODIGO_RENGLON_PADRE VARCHAR2(1024);

-- table index
create index saf.ht_actividades_ser_i1 on saf.ht_actividades_servicos (id_est_cs_actividades);
create index saf.ht_actividades_ser_i162 on saf.ht_actividades_servicos (id_ht_hoja_de_tiempos);
create index saf.ht_actividades_ser_i173 on saf.ht_actividades_servicos (id_ht_renglones_servicos);


-- create tables
create table saf.ht_listado_periodos (
     id                             number generated by default on null as identity
         constraint ht_listado_periodo_id_pk primary key,
     correlativo                    number not null,
     fecha_inicio                   date not null,
     fecha_final                    date not null,
     tipo_periodo                   varchar2(32 char) not null,
     anio                           number not null,
     serie                          varchar2(32 char) not null,
     usuario_grababacion            number not null,
     fecha_grabacion                date default SYSDATE,
     usuario_modificacion           number,
     fecha_modificacion             date
)
;

-- load data

-- Generated by Quick SQL Wednesday January 24, 2024  10:24:48

/*
HT_HOJA_DE_TIEMPOS
    ID NUM /PK,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ESTADO VC100 /DEFAULT INVALIDO,
    TIPO_VISTA NUM /NN,
    USUARIO_GRABACION NUM /NN,
    FECHA_GRABACION DATE /DEFAULT SYSDATE

HT_TAREAS_ADMINISTRATIVAS
    ID NUM /PK,
    ID_HT_HOJA_DE_TIEMPOS NUM /NN /FK HT_HOJA_DE_TIEMPOS,
    ID_PADRE NUM,
    TITULO VC1024 /NN,
    TIPO_REGISTRO VC10 /DEFAULT R,
    FECHA DATE /NN,
    CANTIDAD_HORAS NUM /NN,
    ESTADO VC100 /DEFAULT INVALIDO,
    USUARIO_APROBADOR NUM,
    USUARIO_GRABACION NUM /NN,
    FECHA_GRABACION DATE /DEFAULT SYSDATE,
    USUARIO_MODIFICACION NUM,
    FECHA_MODIFICACION DATE

HT_RENGLONES_SERVICOS
    ID NUM /PK,
    ID_HT_HOJA_DE_TIEMPOS NUM /NN /FK HT_HOJA_DE_TIEMPOS,
    ID_EST_CS_RENGLONES NUM /FK EST_CS_RENGLONES,
    ID_EST_CS_CONTRATOS_SERVICIO NUM /FK EST_CS_CONTRATOS_SERVICIO,
    ID_PADRE NUM,
    TITULO VC1024 /NN,
    TIPO_REGISTRO VC10 /DEFAULT CS,
    FECHA DATE /NN,
    CANTIDAD_HORAS NUM /NN,
    ESTADO VC100 /DEFAULT INVALIDO,
    USUARIO_APROBADOR NUM,
    USUARIO_GRABACION NUM /NN,
    FECHA_GRABACION DATE /DEFAULT SYSDATE,
    USUARIO_MODIFICACION NUM,
    FECHA_MODIFICACION DATE

HT_ACTIVIDADES_SERVICOS
    ID NUM /PK,
    ID_HT_HOJA_DE_TIEMPOS NUM /NN /FK HT_HOJA_DE_TIEMPOS,
    ID_EST_CS_ACTIVIDADES NUM /FK EST_CS_ACTIVIDADES,
    ID_HT_RENGLONES_SERVICOS NUM /FK HT_RENGLONES_SERVICOS,
    TITULO VC1024 /NN,
    TIPO_REGISTRO VC10 /DEFAULT R,
    FECHA DATE /NN,
    CANTIDAD_HORAS NUM /NN,
    ESTADO VC100 /DEFAULT INVALIDO,
    USUARIO_APROBADOR NUM,
    USUARIO_GRABACION NUM /NN,
    FECHA_GRABACION DATE /DEFAULT SYSDATE,
    USUARIO_MODIFICACION NUM,
    FECHA_MODIFICACION DATE

HT_LISTADO_PERIODOS
    ID NUM /PK,
    CORRELATIVO NUM /NN,
    FECHA_INICIO DATE /NN,
    FECHA_FINAL DATE /NN,
    TIPO_PERIODO VC32 /NN,
    ANIO NUM /NN,
    SERIE VC32 /NN,
    USUARIO_GRABABACION NUM /NN,
    FECHA_GRABACION DATE /DEFAULT SYSDATE,
    USUARIO_MODIFICACION NUM,
    FECHA_MODIFICACION DATE

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
