CREATE OR REPLACE FUNCTION SAF.APX_FNC_CONVERSION_MONEDAS(IMPORTE NUMBER, DE NUMBER, A NUMBER, TAsA_DE NUMBER DEFAULT NULL, TAsA_A NUMBER DEFAULT NULL)
    RETURN NUMBER IS

    CURSOR C_MONEDAS IS
        SELECT CODIGO_MONEDA FROM SAF.GRAL_MONEDAS WHERE MONEDA_LOCAL IS NOT NULL;

    V_MONEDA_LOCAL NUMBER := NULL;
BEGIN
    OPEN C_MONEDAS;
        FETCH C_MONEDAS INTO V_MONEDA_LOCAL;
    CLOSE C_MONEDAS;

    IF V_MONEDA_LOCAL IS NOT NULL /*AND IMPORTE > 0*/ THEN
        IF DE = V_MONEDA_LOCAL AND A = V_MONEDA_LOCAL THEN
            RETURN IMPORTE;
        ELSIF DE = V_MONEDA_LOCAL AND A != V_MONEDA_LOCAL THEN
            RETURN IMPORTE / NVL(TAsA_A, SAF.FNC_GET_TIPO_CAMBIO(A));
        ELSIF DE != V_MONEDA_LOCAL AND A = V_MONEDA_LOCAL THEN
            RETURN IMPORTE * NVL(TAsA_DE, SAF.FNC_GET_TIPO_CAMBIO(DE));
        ELSIF DE != V_MONEDA_LOCAL AND A != V_MONEDA_LOCAL THEN
            RETURN (IMPORTE * NVL(TAsA_DE, SAF.FNC_GET_TIPO_CAMBIO(DE))) / NVL(TAsA_A, SAF.FNC_GET_TIPO_CAMBIO(A));
        END IF;
    END IF;

    RETURN 0;
END;