CREATE OR REPLACE FUNCTION SAF.DETALLE_NOTAS_FINANCIERAS_VERSIONAMIENTO_CORPORACION
(
	V_EMPRESA VARCHAR2,
	V_ID_PLANTILLA NUMBER DEFAULT 0,
	V_ID_PADRE NUMBER DEFAULT 0,
	V_INTERCOMPANY VARCHAR DEFAULT 'N',
	V_AGRUPADOR NUMBER,
	V_AGRUPAR_MENOR_A NUMBER DEFAULT 0,
    V_ANIO NUMBER DEFAULT TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')),
    V_MES_INICIO NUMBER DEFAULT 1,
    V_MES_FIN NUMBER DEFAULT 12,
	V_VERSION NUMBER DEFAULT 2020
)
RETURN T_CON_DETALLE_NOTAS AS
    V_T_DETALLE_NOTAS T_CON_DETALLE_NOTAS := T_CON_DETALLE_NOTAS();
   	V_TEMP_DETALLE_NOTAS T_CON_DETALLE_NOTAS := T_CON_DETALLE_NOTAS();
begin	
    IF V_VERSION = 1311 THEN
		RETURN SAF.RETURN_DETALLE_NOTAS_FINANCIERAS_HOMOLOGADAS_CORPORACION
			(
				V_EMPRESA => V_EMPRESA,
				V_ID_PLANTILLA => V_ID_PLANTILLA,
				V_ID_PADRE => V_ID_PADRE,
				V_INTERCOMPANY => V_INTERCOMPANY,
				V_AGRUPADOR => V_AGRUPADOR,
				V_AGRUPAR_MENOR_A => V_AGRUPAR_MENOR_A,
				V_ANIO => V_ANIO,
				V_MES_INICIO => V_MES_INICIO,
				V_MES_FIN => V_MES_FIN,
                V_VERSION => V_VERSION
			);
	ELSE
		RETURN SAF.RETURN_DETALLE_NOTAS_FINANCIERAS_CORPORACION
			(
				V_EMPRESA => V_EMPRESA,
				V_ID_PLANTILLA => V_ID_PLANTILLA,
				V_ID_PADRE => V_ID_PADRE,
				V_INTERCOMPANY => V_INTERCOMPANY,
				V_AGRUPADOR => V_AGRUPADOR,
				V_AGRUPAR_MENOR_A => V_AGRUPAR_MENOR_A,
				V_ANIO => V_ANIO,
				V_MES_INICIO => V_MES_INICIO,
				V_MES_FIN => V_MES_FIN,
                V_VERSION => V_VERSION
			);
	END IF;

END DETALLE_NOTAS_FINANCIERAS_VERSIONAMIENTO_CORPORACION;