CREATE OR REPLACE Function SAF.FNC_GET_REPORTES_FINANCIEROS_SALDO_PRESTAMO
(
    P_CODIGO_USUARIO NUMBER,
    P_COD_CTA VARCHAR2,
    P_MES NUMBER,
    P_EJERCICIO VARCHAR2,
    P_VERSION NUMBER

) RETURN NUMBER IS
       V_MONTO NUMBER;
BEGIN
    IF P_VERSION != 1311 THEN
        SELECT
            NVL(SUM(AA.VALOR), 0)
            INTO
            V_MONTO
        FROM SAF.APX_VW_CON_NOTAS_POLIZASD AA
        WHERE AA.COD_CTA = P_COD_CTA
        AND AA.MES <= P_MES
        AND AA.EJERCICIO = P_EJERCICIO
        AND AA.CODIGO_EMPRESA IN
        (
            SELECT
                DISTINCT
                ID_ASOCIACION
            FROM SAF.REPORTES_FINANCIEROS_CONFIGURACION
            WHERE USUARIO_GRABACION = P_CODIGO_USUARIO
            AND TIPO_REPORTE = 92
        );
    ELSE
        SELECT
            NVL(SUM(AA.VALOR), 0)
            INTO
            V_MONTO
        FROM SAF.APX_VW_CON_NOTAS_POLIZASD_FISCAL_HOMOLOGADAS AA
        WHERE AA.COD_CTA = P_COD_CTA
        AND AA.MES <= P_MES
        AND AA.EJERCICIO = P_EJERCICIO
        AND AA.CODIGO_EMPRESA IN
        (
            SELECT
                DISTINCT
                ID_ASOCIACION
            FROM SAF.REPORTES_FINANCIEROS_CONFIGURACION
            WHERE USUARIO_GRABACION = P_CODIGO_USUARIO
            AND TIPO_REPORTE = 92
        );
    END IF;

    RETURN NVL(V_MONTO, 0);
END;