-- SAF.OBJ_REPORTE_FINANCIERO_EERR_CXU definition

CREATE OR REPLACE TYPE SAF.OBJ_REPORTE_FINANCIERO_EERR_CXU AS OBJECT 
(
    ID NUMBER(10,0),
    NOMBRE VARCHAR2(512),
    CLASE VARCHAR2(512),
    ID_REGISTRO NUMBER(10,0),
    ID_NOTA NUMBER(10,0),
    MES NUMBER(10,5),
    CODIGO_DIVISION varchar2(10),
    VALOR NUMBER(20,5),
    BLOQUE NUMBER(12,5)
);