CREATE OR REPLACE TRIGGER SAF.AUDIT_EST_CS_CONTRATOS_SERVICIO
	AFTER
	INSERT OR UPDATE OR DELETE
	ON SAF.EST_CS_CONTRATOS_SERVICIO
	REFERENCING OLD AS OLD NEW AS NEW
	FOR EACH ROW
DECLARE
	TABLA VARCHAR2(128) := 'EST_CS_CONTRATOS_SERVICIO';
	US GRAL_USUARIOS.CODIGO_USUARIO%TYPE := PCK_GRAL.FNC_TRAE_NO_USUARIO(NVL(V('APP_USER'), USER));
	L_ACCION VARCHAR2(1);
BEGIN
	IF UPDATING THEN
		L_ACCION := 'U';
	ELSIF DELETING THEN
		L_ACCION := 'D';
	END IF;

	IF UPDATING OR DELETING THEN
		IF :OLD.CODIGO_EMPRESA IS NOT NULL AND :NEW.CODIGO_EMPRESA IS NULL
			OR :OLD.CODIGO_EMPRESA IS NULL AND :NEW.CODIGO_EMPRESA IS NOT NULL
			OR :NEW.CODIGO_EMPRESA <> :OLD.CODIGO_EMPRESA THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'CODIGO_EMPRESA', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'NUMBER', :OLD.CODIGO_EMPRESA, :NEW.CODIGO_EMPRESA
			);
		END IF;

        IF :OLD.CODIGO_DIVISION IS NOT NULL AND :NEW.CODIGO_DIVISION IS NULL
			OR :OLD.CODIGO_DIVISION IS NULL AND :NEW.CODIGO_DIVISION IS NOT NULL
			OR :NEW.CODIGO_DIVISION <> :OLD.CODIGO_DIVISION THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'CODIGO_DIVISION', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'NUMBER', :OLD.CODIGO_DIVISION, :NEW.CODIGO_DIVISION
			);
		END IF;

        IF :OLD.CODIGO_PROYECTO IS NOT NULL AND :NEW.CODIGO_PROYECTO IS NULL
			OR :OLD.CODIGO_PROYECTO IS NULL AND :NEW.CODIGO_PROYECTO IS NOT NULL
			OR :NEW.CODIGO_PROYECTO <> :OLD.CODIGO_PROYECTO THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'CODIGO_PROYECTO', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'VARCHAR2(256)', :OLD.CODIGO_PROYECTO, :NEW.CODIGO_PROYECTO
			);
		END IF;

        IF :OLD.NUMERO_CUENTA IS NOT NULL AND :NEW.NUMERO_CUENTA IS NULL
			OR :OLD.NUMERO_CUENTA IS NULL AND :NEW.NUMERO_CUENTA IS NOT NULL
			OR :NEW.NUMERO_CUENTA <> :OLD.NUMERO_CUENTA THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'NUMERO_CUENTA', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'NUMBER', :OLD.NUMERO_CUENTA, :NEW.NUMERO_CUENTA
			);
		END IF;

        IF :OLD.CODIGO_MONEDA IS NOT NULL AND :NEW.CODIGO_MONEDA IS NULL
			OR :OLD.CODIGO_MONEDA IS NULL AND :NEW.CODIGO_MONEDA IS NOT NULL
			OR :NEW.CODIGO_MONEDA <> :OLD.CODIGO_MONEDA THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'CODIGO_MONEDA', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'NUMBER', :OLD.CODIGO_MONEDA, :NEW.CODIGO_MONEDA
			);
		END IF;

        IF :OLD.TASA_CAMBIO IS NOT NULL AND :NEW.TASA_CAMBIO IS NULL
			OR :OLD.TASA_CAMBIO IS NULL AND :NEW.TASA_CAMBIO IS NOT NULL
			OR :NEW.TASA_CAMBIO <> :OLD.TASA_CAMBIO THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'TASA_CAMBIO', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'NUMBER(10,5)', :OLD.TASA_CAMBIO, :NEW.TASA_CAMBIO
			);
		END IF;

        IF :OLD.ESTADO_RESOLUCION IS NOT NULL AND :NEW.ESTADO_RESOLUCION IS NULL
			OR :OLD.ESTADO_RESOLUCION IS NULL AND :NEW.ESTADO_RESOLUCION IS NOT NULL
			OR :NEW.ESTADO_RESOLUCION <> :OLD.ESTADO_RESOLUCION THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'ESTADO_RESOLUCION', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'VARCHAR2(256)', :OLD.ESTADO_RESOLUCION, :NEW.ESTADO_RESOLUCION
			);
		END IF;

        IF :OLD.FECHA_ENTREGA IS NOT NULL AND :NEW.FECHA_ENTREGA IS NULL
			OR :OLD.FECHA_ENTREGA IS NULL AND :NEW.FECHA_ENTREGA IS NOT NULL
			OR :NEW.FECHA_ENTREGA <> :OLD.FECHA_ENTREGA THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'FECHA_ENTREGA', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'DATE', :OLD.FECHA_ENTREGA, :NEW.FECHA_ENTREGA
			);
		END IF;

        IF :OLD.ALCANCE_TRABAJO IS NOT NULL AND :NEW.ALCANCE_TRABAJO IS NULL
			OR :OLD.ALCANCE_TRABAJO IS NULL AND :NEW.ALCANCE_TRABAJO IS NOT NULL
			OR :NEW.ALCANCE_TRABAJO <> :OLD.ALCANCE_TRABAJO THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'ALCANCE_TRABAJO', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'VARCHAR2(1024)', :OLD.ALCANCE_TRABAJO, :NEW.ALCANCE_TRABAJO
			);
		END IF;

        IF :OLD.TITULO_CONTRATO IS NOT NULL AND :NEW.TITULO_CONTRATO IS NULL
			OR :OLD.TITULO_CONTRATO IS NULL AND :NEW.TITULO_CONTRATO IS NOT NULL
			OR :NEW.TITULO_CONTRATO <> :OLD.TITULO_CONTRATO THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'TITULO_CONTRATO', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'VARCHAR2(256)', :OLD.TITULO_CONTRATO, :NEW.TITULO_CONTRATO
			);
		END IF;

        IF :OLD.GERENTE_RESPONSABLE IS NOT NULL AND :NEW.GERENTE_RESPONSABLE IS NULL
			OR :OLD.GERENTE_RESPONSABLE IS NULL AND :NEW.GERENTE_RESPONSABLE IS NOT NULL
			OR :NEW.GERENTE_RESPONSABLE <> :OLD.GERENTE_RESPONSABLE THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'GERENTE_RESPONSABLE', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'NUMBER(10,0)', :OLD.GERENTE_RESPONSABLE, :NEW.GERENTE_RESPONSABLE
			);
		END IF;

        IF :OLD.TIPO_CONTRATO IS NOT NULL AND :NEW.TIPO_CONTRATO IS NULL
			OR :OLD.TIPO_CONTRATO IS NULL AND :NEW.TIPO_CONTRATO IS NOT NULL
			OR :NEW.TIPO_CONTRATO <> :OLD.TIPO_CONTRATO THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'TIPO_CONTRATO', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'NUMBER(5,0)', :OLD.TIPO_CONTRATO, :NEW.TIPO_CONTRATO
			);
		END IF;

        IF :OLD.FECHA_INICIO IS NOT NULL AND :NEW.FECHA_INICIO IS NULL
			OR :OLD.FECHA_INICIO IS NULL AND :NEW.FECHA_INICIO IS NOT NULL
			OR :NEW.FECHA_INICIO <> :OLD.FECHA_INICIO THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'FECHA_INICIO', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'DATE', :OLD.FECHA_INICIO, :NEW.FECHA_INICIO
			);
		END IF;

        IF :OLD.FECHA_FIN IS NOT NULL AND :NEW.FECHA_FIN IS NULL
			OR :OLD.FECHA_FIN IS NULL AND :NEW.FECHA_FIN IS NOT NULL
			OR :NEW.FECHA_FIN <> :OLD.FECHA_FIN THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'FECHA_FIN', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'DATE', :OLD.FECHA_FIN, :NEW.FECHA_FIN
			);
		END IF;

        IF :OLD.MONTO_ANTICIPO IS NOT NULL AND :NEW.MONTO_ANTICIPO IS NULL
			OR :OLD.MONTO_ANTICIPO IS NULL AND :NEW.MONTO_ANTICIPO IS NOT NULL
			OR :NEW.MONTO_ANTICIPO <> :OLD.MONTO_ANTICIPO THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'MONTO_ANTICIPO', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'NUMBER(24,5)', :OLD.MONTO_ANTICIPO, :NEW.MONTO_ANTICIPO
			);
		END IF;

        IF :OLD.PORCENTAJE_ANTICIPO IS NOT NULL AND :NEW.PORCENTAJE_ANTICIPO IS NULL
			OR :OLD.PORCENTAJE_ANTICIPO IS NULL AND :NEW.PORCENTAJE_ANTICIPO IS NOT NULL
			OR :NEW.PORCENTAJE_ANTICIPO <> :OLD.PORCENTAJE_ANTICIPO THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'PORCENTAJE_ANTICIPO', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'NUMBER(10,5)', :OLD.PORCENTAJE_ANTICIPO, :NEW.PORCENTAJE_ANTICIPO
			);
		END IF;

        IF :OLD.PORCENTAJE_INDIRECTO IS NOT NULL AND :NEW.PORCENTAJE_INDIRECTO IS NULL
			OR :OLD.PORCENTAJE_INDIRECTO IS NULL AND :NEW.PORCENTAJE_INDIRECTO IS NOT NULL
			OR :NEW.PORCENTAJE_INDIRECTO <> :OLD.PORCENTAJE_INDIRECTO THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'PORCENTAJE_INDIRECTO', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'NUMBER(10,5)', :OLD.PORCENTAJE_INDIRECTO, :NEW.PORCENTAJE_INDIRECTO
			);
		END IF;

        IF :OLD.PORCENTAJE_RETENIDO IS NOT NULL AND :NEW.PORCENTAJE_RETENIDO IS NULL
			OR :OLD.PORCENTAJE_RETENIDO IS NULL AND :NEW.PORCENTAJE_RETENIDO IS NOT NULL
			OR :NEW.PORCENTAJE_RETENIDO <> :OLD.PORCENTAJE_RETENIDO THEN
			INSERT INTO SAF.HISTORY
			(
				ID, TABLE_NAME, COLUMN_NAME, PK1, TAB_ROW_VERSION, ACTION, ACTION_DATE, ACTION_BY, DATA_TYPE, OLD_VC, NEW_VC
			)
			VALUES
			(
				HISTORY_SEQ.NEXTVAL, TABLA, 'PORCENTAJE_RETENIDO', :OLD.ID, NULL, L_ACCION, SYSDATE, US, 'NUMBER(10,5)', :OLD.PORCENTAJE_RETENIDO, :NEW.PORCENTAJE_RETENIDO
			);
		END IF;
	END IF;
END;