-- create tables
create table cts_tipo_servicio (
    id                             number generated by default on null as identity 
                                   constraint cts_tipo_servicio_id_pk primary key,
    descripcion                    varchar2(1024 char),
    activo                         varchar2(10 char) default 'S',
    usuario_grabacion              number(10,0),
    fecha_grabacion                date default SYSDATE,
    usuario_modificacion           number(10,0),
    fecha_modificacion             date
)
;

-- load data
 
-- Generated by Quick SQL Tuesday October 24, 2023  17:23:41
 
/*
CTS_TIPO_SERVICIO
    ID NUMBER /PK,
    DESCRIPCION VC1024,
    ACTIVO VC5 /DEFAULT S,
    USUARIO_GRABACION NUMBER(10,0),
    FECHA_GRABACION DATE /DEFAULT SYSDATE,
    USUARIO_MODIFICACION NUMBER(10,0),
    FECHA_MODIFICACION DATE

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
