-- create tables
create table saf.est_cs_plantillas (
    id                             number generated by default on null as identity 
                                   constraint est_cs_plantillas_id_pk primary key,
    nombre                         varchar2(256 char),
    estado                         varchar2(64 char),
    codigo_division                number(10,0),
    usuario_grabacion              number(10,0)
                                   constraint est_cs_planti_usuario_graba_fk
                                   references saf.gral_usuarios on delete cascade,
    fecha_grabacion                date default SYSDATE,
    usuario_modificacion           number(10,0)
                                   constraint est_cs_planti_usuario_modif_fk
                                   references saf.gral_usuarios on delete cascade,
    fecha_modificacion             date
)
;

-- table index
create index est_cs_plantillas_i1 on saf.est_cs_plantillas (usuario_grabacion);
create index est_cs_plantillas_i42 on saf.est_cs_plantillas (usuario_modificacion);

-- load data
 
-- Generated by Quick SQL Tuesday October 24, 2023  17:12:29
 
/*
EST_CS_PLANTILLAS
    ID NUMBER /PK,
    NOMBRE VC256,
    ESTADO VC64,
    CODIGO_DIVISION NUMBER(10,0),
    USUARIO_GRABACION NUMBER(10,0) /FK GRAL_USUARIOS,
    FECHA_GRABACION DATE /DEFAULT SYSDATE,
    USUARIO_MODIFICACION NUMBER(10,0) /FK GRAL_USUARIOS,
    FECHA_MODIFICACION DATE

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
