-- create tables
create table saf.est_cs_contratos_servicio (
    id                             number generated by default on null as identity 
                                   constraint est_cs_contratos_s_id_pk primary key,
    codigo_empresa                 number
                                   constraint est_cs_contra_codigo_empres_fk
                                   references gral_empresas on delete cascade,
    codigo_division                number
                                   constraint est_cs_contra_codigo_divisi_fk
                                   references gral_divisiones on delete cascade,
    codigo_proyecto                varchar2(256 char),
    numero_cuenta                  number,
    codigo_moneda                  number
                                   constraint est_cs_contrato_codigo_mone_fk
                                   references gral_monedas on delete cascade,
    tasa_cambio                    number(10,5),
    estado_resolucion              varchar2(256 char),
    fecha_entrega                  date,
    alcance_trabajo                varchar2(1024 char),
    titulo_contrato                varchar2(256 char),
    gerente_responsable            number(10,0)
                                   constraint est_cs_contra_gerente_respo_fk
                                   references gral_usuarios on delete cascade,
    tipo_contrato                  number(5,0),
    fecha_inicio                   date,
    fecha_fin                      date,
    monto_anticipo                 number(24,5),
    porcentaje_anticipo            number(5,5),
    porcentaje_retenido            number(5,5),
    usuario_grabacion              number(10,0)
                                   constraint est_cs_contra_usuario_graba_fk
                                   references gral_usuarios on delete cascade,
    fecha_grabacion                date default SYSDATE,
    usuario_modificacion           number(10,0)
                                   constraint est_cs_contra_usuario_modif_fk
                                   references gral_usuarios on delete cascade,
    fecha_modificacion             date
)
;

-- table index
create index est_cs_contratos_s_i1 on saf.est_cs_contratos_servicio (codigo_division);
create index est_cs_contratos_s_i82 on saf.est_cs_contratos_servicio (codigo_empresa);
create index est_cs_contratos_s_i93 on saf.est_cs_contratos_servicio (codigo_moneda);
create index est_cs_contratos_s_i104 on saf.est_cs_contratos_servicio (gerente_responsable);
create index est_cs_contratos_s_i115 on saf.est_cs_contratos_servicio (usuario_grabacion);
create index est_cs_contratos_s_i126 on saf.est_cs_contratos_servicio (usuario_modificacion);

-- load data
 
-- Generated by Quick SQL Tuesday October 24, 2023  17:18:56
 
/*
EST_CS_CONTRATOS_SERVICIO
    ID NUMBER /PK,
    CODIGO_EMPRESA NUMBER /FK GRAL_EMPRESAS,
    CODIGO_DIVISION NUMBER /FK GRAL_DIVISIONES,
    CODIGO_PROYECTO VC256,
    NUMERO_CUENTA NUMBER,
    CODIGO_MONEDA NUMBER /FK GRAL_MONEDAS,
    TASA_CAMBIO NUMBER(10,5),
    ESTADO_RESOLUCION VC256,
    FECHA_ENTREGA DATE,
    ALCANCE_TRABAJO VC1024,
    TITULO_CONTRATO VC256,
    GERENTE_RESPONSABLE NUMBER(10,0) /FK GRAL_USUARIOS,
    TIPO_CONTRATO NUMBER(5,0),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    MONTO_ANTICIPO NUMBER(24,5),
    PORCENTAJE_ANTICIPO NUMBER(5,5),
    PORCENTAJE_RETENIDO NUMBER(5,5),
    USUARIO_GRABACION NUMBER(10,0) /FK GRAL_USUARIOS,
    FECHA_GRABACION DATE /DEFAULT SYSDATE,
    USUARIO_MODIFICACION NUMBER(10,0) /FK GRAL_USUARIOS,
    FECHA_MODIFICACION DATE

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
