-- create tables
create table saf.est_cs_actividades (
    id                             number generated by default on null as identity 
                                   constraint est_cs_actividades_id_pk primary key,
    id_est_cs_renglones            number
                                   constraint est_cs_activi_id_est_cs_ren_fk
                                   references est_cs_renglones on delete cascade,
    orden                          number(10,0) default '1',
    titulo                         varchar2(256 char),
    descripcion                    varchar2(1024 char),
    codigo_medida                  number
                                   constraint est_cs_activida_codigo_medi_fk
                                   references gral_medidas on delete cascade,
    codigo_actividad               varchar2(256 char),
    costo_unitario                 number(24,5),
    costo_total                    number(24,5),
    indirecto_porcentaje           number(24,5),
    indirecto                      number(24,5),
    cantidad                       number(20,5),
    indirecto                      number(24,5),
    precio_unitario                number(24,5),
    precio_total                   number(24,5),
    id_est_cs_plantilla_actividade number
                                   constraint est_cs_activi_id_est_cs_pla_fk
                                   references est_cs_plantillas_actividades on delete cascade,
    usuario_grabacion              number(10,0)
                                   constraint est_cs_activi_usuario_graba_fk
                                   references gral_usuarios on delete cascade,
    fecha_grabacion                date default SYSDATE,
    usuario_modificacion           number(10,0)
                                   constraint est_cs_activi_usuario_modif_fk
                                   references gral_usuarios on delete cascade,
    fecha_modificacion             date
)
;

-- table index
create index est_cs_actividades_i1 on saf.est_cs_actividades (codigo_medida);
create index est_cs_actividades_i72 on saf.est_cs_actividades (id_est_cs_plantilla_actividade);
create index est_cs_actividades_i83 on saf.est_cs_actividades (id_est_cs_renglones);
create index est_cs_actividades_i94 on saf.est_cs_actividades (usuario_grabacion);
create index est_cs_actividades_i105 on saf.est_cs_actividades (usuario_modificacion);

-- load data
 
-- Generated by Quick SQL Tuesday October 24, 2023  17:22:06
 
/*
EST_CS_ACTIVIDADES
    ID NUMBER /PK,
    ID_EST_CS_RENGLONES NUMBER /FK EST_CS_RENGLONES,
    ORDEN NUMBER(10,0) /DEFAULT 1,
    TITULO VC256,
    DESCRIPCION VC1024,
    CODIGO_MEDIDA NUMBER /FK GRAL_MEDIDAS,
    CODIGO_ACTIVIDAD VC256,
    COSTO_UNITARIO NUMBER(24,5),
    COSTO_TOTAL NUMBER(24,5),
    INDIRECTO_PORCENTAJE NUMBER(5,5),
    INDIRECTO NUMBER(24,5),
    PRECIO_UNITARIO NUMBER(24,5),
    PRECIO_TOTAL NUMBER(24,5),
    ID_EST_CS_PLANTILLA_ACTIVIDADES NUMBER /FK EST_CS_PLANTILLA_ACTIVIDADES,
    USUARIO_GRABACION NUMBER(10,0) /FK GRAL_USUARIOS,
    FECHA_GRABACION DATE /DEFAULT SYSDATE,
    USUARIO_MODIFICACION NUMBER(10,0) /FK GRAL_USUARIOS,
    FECHA_MODIFICACION DATE

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
