-- create tables
create table saf.est_tipo_contrato (
    id                             number generated by default on null as identity 
                                   constraint est_tipo_contrato_id_pk primary key,
    descripcion                    varchar2(256 char) not null,
    activo                         varchar2(1 char) default 'S',
    usuario_grabacion              number not null,
    fecha_grabacion                date default SYSDATE,
    usuario_modificacion           number,
    fecha_modificacion             date
)
;

-- load data
 
-- Generated by Quick SQL Wednesday October 18, 2023  10:42:54
 
/*
EST_TIPO_CONTRATO
    ID NUM /PK,
    DESCRIPCION VC256 /NN,
    ACTIVO VC1 /DEFAULT S,
    USUARIO_GRABACION NUM /NN,
    FECHA_GRABACION DATE /DEFAULT SYSDATE,
    USUARIO_MODIFICACION NUM,
    FECHA_MODIFICACION DATE

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
