-- create tables
create table saf.est_cs_actividad_labor (
    id                             number generated by default on null as identity 
                                   constraint est_cs_actividad_l_id_pk primary key,
    id_est_cs_actividades          number
                                   constraint est_cs_activi_id_est_cs_act_fk
                                   references est_cs_actividades on delete cascade,
    id_dhc_descriptor_puesto       number
                                   constraint est_cs_activi_id_dhc_descri_fk
                                   references dhc_descriptor_puesto on delete cascade,
    codigo_medida                  number
                                   constraint est_cs_activida_labor_codigo_medi_fk
                                   references gral_medidas on delete cascade,
    cantidad                       number(20,5),
    costo_unitario                 number(24,5),
    costo_total                    number(24,5),
    usuario_grabacion              number(10,0)
                                   constraint est_cs_activi_labor_usuario_graba_fk
                                   references gral_usuarios on delete cascade,
    fecha_grabacion                date default SYSDATE,
    usuario_modificacion           number(10,0)
                                   constraint est_cs_activi_labor_usuario_modif_fk
                                   references gral_usuarios on delete cascade,
    fecha_modificacion             date
)
;

-- table index
create index est_cs_actividad_l_i1 on est_cs_actividad_labor (codigo_medida);
create index est_cs_actividad_l_i72 on est_cs_actividad_labor (id_dhc_descriptor_puesto);
create index est_cs_actividad_l_i83 on est_cs_actividad_labor (id_est_cs_actividades);
create index est_cs_actividad_l_i94 on est_cs_actividad_labor (usuario_grabacion);
create index est_cs_actividad_l_i105 on est_cs_actividad_labor (usuario_modificacion);

-- load data
 
-- Generated by Quick SQL Friday December 01, 2023  10:27:00
 
/*
EST_CS_ACTIVIDAD_LABOR
    ID NUMBER /PK,
    ID_EST_CS_ACTIVIDADES NUMBER /FK EST_CS_ACTIVIDADES,
    ID_DHC_DESCRIPTOR_PUESTO /FK DHC_DESCRIPTOR_PUESTO,
    CODIGO_MEDIDA NUMBER /FK GRAL_MEDIDAS,
    CANTIDAD NUMBER(20,5),
    COSTO_UNITARIO NUMBER(24,5),
    COSTO_TOTAL NUMBER(24,5),
    USUARIO_GRABACION NUMBER(10,0) /FK GRAL_USUARIOS,
    FECHA_GRABACION DATE /DEFAULT SYSDATE,
    USUARIO_MODIFICACION NUMBER(10,0) /FK GRAL_USUARIOS,
    FECHA_MODIFICACION DATE

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
