-- create tables
create table saf.est_cs_renglones_lista (
    id                             number generated by default on null as identity 
                                   constraint est_cs_renglones_l_id_pk primary key,
    codigo_renglon                 varchar2(256 char),
    codigo_renglon_padre           varchar2(256 char),
    titulo                         varchar2(256 char),
    descripcion                    varchar2(1024 char),
    codigo_medida                  number
                                   constraint est_cs_renglone_codigo_medi_fk
                                   references gral_medidas on delete cascade,
    tipo_costo                     number(5,0),
    estado                         number(5,0),
    usuario_grabacion              number(10,0)
                                   constraint est_cs_renglo_lista_usuario_graba_fk
                                   references gral_usuarios on delete cascade,
    fecha_grabacion                date default SYSDATE,
    usuario_modificacion           number(10,0)
                                   constraint est_cs_renglo_lista_usuario_modif_fk
                                   references gral_usuarios on delete cascade,
    fecha_modificacion             date
)
;

-- table index
create index est_cs_renglones_l_i1 on est_cs_renglones_lista (codigo_medida);
create index est_cs_renglones_l_i52 on est_cs_renglones_lista (usuario_grabacion);
create index est_cs_renglones_l_i63 on est_cs_renglones_lista (usuario_modificacion);

-- load data
 
-- Generated by Quick SQL Monday December 04, 2023  10:46:32
 
/*
EST_CS_RENGLONES_LISTA
    ID NUMBER /PK,
    CODIGO_RENGLON VC256,
    CODIGO_RENGLON_PADRE VC256,
    TITULO VC256,
    DESCRIPCION VC1024,
    CODIGO_MEDIDA NUMBER /FK GRAL_MEDIDAS,
    TIPO_COSTO NUMBER(5,0),
    ESTADO NUMBER(5,0),
    USUARIO_GRABACION NUMBER(10,0) /FK GRAL_USUARIOS,
    FECHA_GRABACION DATE /DEFAULT SYSDATE,
    USUARIO_MODIFICACION NUMBER(10,0) /FK GRAL_USUARIOS,
    FECHA_MODIFICACION DATE

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
