-- create tables
create table saf.est_cs_renglones (
    id                             number generated by default on null as identity 
                                   constraint est_cs_renglones_id_pk primary key,
    id_cs_contratos_servicio       number
                                   constraint est_cs_renglo_id_cs_contrat_fk
                                   references est_cs_contratos_servicio on delete cascade,
    id_cts_tipo_servicio           number
                                   constraint est_cs_renglo_id_cts_tipo_s_fk
                                   references cts_tipo_servicio on delete cascade,
    codigo_renglon                 varchar2(256 char),
    codigo_renglon_padre           varchar2(256 char),
    orden                          number(10,0) default '1',
    titulo                         varchar2(256 char),
    descripcion                    varchar2(1024 char),
    codigo_medida                  number,
    tipo_costo                     number(5,0),
    costo_unitario                 number(24,5),
    costo_total                    number(24,5),
    indirecto_porcentaje           number(5,5),
    indirecto                      number(24,5),
    precio_unitario                number(24,5),
    precio_total                   number(24,5),
    id_est_cs_plantilla_renglones  number
                                   constraint est_cs_renglo_id_est_cs_pla_fk
                                   references est_cs_plantillas_renglones on delete cascade,
    usuario_grabacion              number(10,0)
                                   constraint est_cs_renglo_usuario_graba_fk
                                   references gral_usuarios on delete cascade,
    fecha_grabacion                date default SYSDATE,
    usuario_modificacion           number(10,0)
                                   constraint est_cs_renglo_usuario_modif_fk
                                   references gral_usuarios on delete cascade,
    fecha_modificacion             date
)
;


-- table index
create index est_cs_renglones_i1 on saf.est_cs_renglones (id_cs_contratos_servicio);
create index est_cs_renglones_i72 on saf.est_cs_renglones (id_cts_tipo_servicio);
create index est_cs_renglones_i83 on saf.est_cs_renglones (id_est_cs_plantilla_renglones);
create index est_cs_renglones_i94 on saf.est_cs_renglones (usuario_grabacion);
create index est_cs_renglones_i105 on saf.est_cs_renglones (usuario_modificacion);

-- load data
 
-- Generated by Quick SQL Tuesday October 24, 2023  17:20:59
 
/*
EST_CS_RENGLONES
    ID NUMBER /PK,
    ID_CS_CONTRATOS_SERVICIO NUMBER /FK EST_CS_CONTRATOS_SERVICIO,
    ID_CTS_TIPO_SERVICIO NUMBER /FK CTS_TIPO_SERVICIO,
    CODIGO_RENGLON VC256,
    CODIGO_RENGLON_PADRE VC256,
    ORDEN NUMBER(10,0) /DEFAULT 1,
    TITULO VC256,
    DESCRIPCION VC1024,
    CODIGO_MEDIDA NUMBER,
    TIPO_COSTO NUMBER(5,0),
    COSTO_UNITARIO NUMBER(24,5),
    COSTO_TOTAL NUMBER(24,5),
    INDIRECTO_PORCENTAJE NUMBER(5,5),
    INDIRECTO NUMBER(24,5),
    PRECIO_UNITARIO NUMBER(24,5),
    PRECIO_TOTAL NUMBER(24,5),
    ID_EST_CS_PLANTILLA_RENGLONES NUMBER /FK EST_CS_PLANTILLA_RENGLONES,
    USUARIO_GRABACION NUMBER(10,0) /FK GRAL_USUARIOS,
    FECHA_GRABACION DATE /DEFAULT SYSDATE,
    USUARIO_MODIFICACION NUMBER(10,0) /FK GRAL_USUARIOS,
    FECHA_MODIFICACION DATE

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
