CREATE OR REPLACE FUNCTION SAF.EST_CS_GET_GENERADOR_CODIGOS
(
    V_CONTRATO_ID NUMBER,
    V_TIPO_RENGLON NUMBER,
    V_CODIGO_PADRE VARCHAR2 DEFAULT NULL,
    V_TIPO_CODIGO NUMBER DEFAULT 1
)
    RETURN VARCHAR2 AS

    CURSOR C_CODIGO_NUMERICO_RENGLON(P_CONTRATO NUMBER) IS
        SELECT
            NVL(MAX(TO_NUMBER(CODIGO_RENGLON)), 0) + 1
        FROM SAF.EST_CS_RENGLONES
        WHERE TIPO_RENGLON = 1
        AND ID_CS_CONTRATOS_SERVICIO = P_CONTRATO;

    CURSOR C_CODIGO_NUMERICO_SERVICIO(P_CONTRATO NUMBER, P_CODIGO_PADRE VARCHAR2) IS
        WITH CORRELATIVO AS
        (
            SELECT
                TO_NUMBER(REPLACE(CODIGO_RENGLON, P_CODIGO_PADRE || '.', '')) CODIGOS
            FROM SAF.EST_CS_RENGLONES
            WHERE TIPO_RENGLON = 2
              AND ID_CS_CONTRATOS_SERVICIO = P_CONTRATO
              AND CODIGO_RENGLON_PADRE = P_CODIGO_PADRE
        )
        SELECT
            NVL(MAX(CODIGOS), 0) + 1
        FROM CORRELATIVO;

    V_CODIGO NUMBER;
    V_CONTADOR VARCHAR2(1024);
BEGIN
    IF
        V_TIPO_CODIGO = 1 THEN
            IF V_TIPO_RENGLON = 1 THEN
                OPEN C_CODIGO_NUMERICO_RENGLON(V_CONTRATO_ID);
                    FETCH C_CODIGO_NUMERICO_RENGLON INTO V_CODIGO;
                CLOSE C_CODIGO_NUMERICO_RENGLON;

                V_CONTADOR := LPAD(V_CODIGO,2,'0');
            ELSIF V_TIPO_RENGLON = 2 THEN
                OPEN C_CODIGO_NUMERICO_SERVICIO(V_CONTRATO_ID, V_CODIGO_PADRE);
                    FETCH C_CODIGO_NUMERICO_SERVICIO INTO V_CODIGO;
                CLOSE C_CODIGO_NUMERICO_SERVICIO;

                V_CONTADOR := V_CODIGO_PADRE || '.' || LPAD(V_CODIGO,2,'0');
            ELSE NULL;
            END IF;
        ELSE NULL;
    END IF;

    RETURN V_CONTADOR;
END EST_CS_GET_GENERADOR_CODIGOS;