create table saf.est_cs_plantillas_actividades (
    id                             number generated by default on null as identity 
                                   constraint est_cs_plantillas_actividad_id_pk primary key,
    id_est_cs_plantillas_renglones number
                                   constraint est_cs_planti_renglones_id_est_cs_pla_fk
                                   references est_cs_plantillas_renglones on delete cascade,
    orden                          number(10,0) default '1',
    titulo                         varchar2(256 char),
    descripcion                    varchar2(1024 char),
    codigo_medida                  number
                                   constraint est_cs_plantill_actividad_codigo_medi_fk
                                   references gral_medidas on delete cascade,
    codigo_actividad               varchar2(256 char),
    usuario_grabacion              number(10,0)
                                   constraint est_cs_plantillas_actividad_graba_fk
                                   references gral_usuarios on delete cascade,
    fecha_grabacion                date default SYSDATE,
    usuario_modificacion           number(10,0)
                                   constraint est_cs_plantillas_actividad_modif_fk
                                   references gral_usuarios on delete cascade,
    fecha_modificacion             date
)
;

-- table index
create index est_cs_plantillas_i3 on saf.est_cs_plantillas_actividades (codigo_medida);
create index est_cs_plantillas_i62 on saf.est_cs_plantillas_actividades (id_est_cs_plantillas_renglones);
create index est_cs_plantillas_i73 on saf.est_cs_plantillas_actividades (usuario_grabacion);
create index est_cs_plantillas_i84 on saf.est_cs_plantillas_actividades (usuario_modificacion);

-- load data
 
-- Generated by Quick SQL Tuesday October 24, 2023  17:15:24
 
/*
EST_CS_PLANTILLAS_ACTIVIDADES
    ID NUMBER /PK,
    ID_EST_CS_PLANTILLAS_RENGLONES NUMBER /FK EST_CS_PLANTILLAS_RENGLONES,
    ORDEN NUMBER(10,0) /DEFAULT 1,
    TITULO VC256,
    DESCRIPCION VC1024,
    CODIGO_MEDIDA NUMBER /FK GRAL_MEDIDAS,
    CODIGO_ACTIVIDAD VC256,
    USUARIO_GRABACION NUMBER(10,0) /FK GRAL_USUARIOS,
    FECHA_GRABACION DATE /DEFAULT SYSDATE,
    USUARIO_MODIFICACION NUMBER(10,0) /FK GRAL_USUARIOS,
    FECHA_MODIFICACION DATE

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
