CREATE OR REPLACE FUNCTION SAF.GET_CODIGOS_UNICOS_RENGLONES
(
	V_NOMBRE_TABLA VARCHAR2,
    V_ID NUMBER,
    V_CODIGO_RENGLON VARCHAR2
)
RETURN NUMBER AS
    V_CONTADOR NUMBER := 0;
    V_CONTADOR_AUX NUMBER := 0;
BEGIN
    IF V_NOMBRE_TABLA = 'EST_CONTRATOS_RENGLONES' AND V_CODIGO_RENGLON IS NOT NULL THEN
        SELECT
            COUNT(RENGLONID)
        INTO
            V_CONTADOR
        FROM SAF.EST_CONTRATOS_RENGLONES
        WHERE CONTRATOID = V_ID
        AND UPPER(CODIGO_RENGLON) = UPPER(V_CODIGO_RENGLON);
    ELSIF V_NOMBRE_TABLA = 'EST_CS_PLANTILLAS_RENGLONES' AND V_CODIGO_RENGLON IS NOT NULL THEN
        SELECT
            COUNT(ID)
        INTO
            V_CONTADOR
        FROM SAF.EST_CS_PLANTILLAS_RENGLONES
        WHERE ID_EST_CS_PLANTILLAS = V_ID
        AND UPPER(CODIGO_RENGLON) = UPPER(V_CODIGO_RENGLON);
    ELSIF V_NOMBRE_TABLA = 'EST_CS_PLANTILLAS_ACTIVIDADES' AND V_CODIGO_RENGLON IS NOT NULL THEN
        SELECT
            COUNT(ID)
        INTO
            V_CONTADOR
        FROM SAF.EST_CS_PLANTILLAS_ACTIVIDADES
        WHERE ID_EST_CS_PLANTILLAS = V_ID
        AND UPPER(CODIGO_ACTIVIDAD) = UPPER(V_CODIGO_RENGLON);
     ELSIF V_NOMBRE_TABLA = 'EST_CS_RENGLONES' AND V_CODIGO_RENGLON IS NOT NULL THEN
        SELECT
            COUNT(A.ID)
        INTO
            V_CONTADOR
        FROM SAF.EST_CS_ACTIVIDADES A
        INNER JOIN SAF.EST_CS_RENGLONES B
            ON B.ID = A.ID_EST_CS_RENGLONES
            AND B.ID_CS_CONTRATOS_SERVICIO = 1
        WHERE UPPER(A.CODIGO_ACTIVIDAD) = UPPER(V_CODIGO_RENGLON);

        SELECT
            COUNT(ID)
        INTO
            V_CONTADOR_AUX
        FROM SAF.EST_CS_RENGLONES
        WHERE ID_CS_CONTRATOS_SERVICIO = V_ID
        AND UPPER(CODIGO_RENGLON) = UPPER(V_CODIGO_RENGLON);

        V_CONTADOR := V_CONTADOR + V_CONTADOR_AUX;
    ELSIF V_NOMBRE_TABLA = 'EST_CS_ACTIVIDADES' AND V_CODIGO_RENGLON IS NOT NULL THEN
        SELECT
            COUNT(A.ID)
        INTO
            V_CONTADOR
        FROM SAF.EST_CS_ACTIVIDADES A
        INNER JOIN SAF.EST_CS_RENGLONES B
            ON B.ID = A.ID_EST_CS_RENGLONES
            AND B.ID_CS_CONTRATOS_SERVICIO = 1
        WHERE UPPER(A.CODIGO_ACTIVIDAD) = UPPER(V_CODIGO_RENGLON);

        SELECT
            COUNT(ID)
        INTO
            V_CONTADOR_AUX
        FROM SAF.EST_CS_RENGLONES
        WHERE ID_CS_CONTRATOS_SERVICIO = V_ID
        AND UPPER(CODIGO_RENGLON) = UPPER(V_CODIGO_RENGLON);

        V_CONTADOR := V_CONTADOR + V_CONTADOR_AUX;
    END IF;

    RETURN V_CONTADOR;
END GET_CODIGOS_UNICOS_RENGLONES;