CREATE OR REPLACE FUNCTION SAF.GET_CODIGOS_UNICOS_RENGLONES
(
	V_NOMBRE_TABLA VARCHAR2,
    V_ID NUMBER,
    V_CODIGO_RENGLON VARCHAR2
)
RETURN NUMBER AS
    V_CONTADOR NUMBER := 0;
BEGIN
    IF V_NOMBRE_TABLA = 'EST_CONTRATOS_RENGLONES' AND V_CODIGO_RENGLON IS NOT NULL THEN
        SELECT
            COUNT(RENGLONID)
        INTO
            V_CONTADOR
        FROM SAF.EST_CONTRATOS_RENGLONES
        WHERE CONTRATOID = V_ID
        AND CODIGO_RENGLON = V_CODIGO_RENGLON;
    END IF;

    RETURN V_CONTADOR;
END GET_CODIGOS_UNICOS_RENGLONES;