-- create tables
create table SAF.FDU_TRANSACCIONES_FINANCIERAS_PAGOS_CAPITAL (
    id                             number generated by default on null as identity 
                                   constraint PK_FDU_TRANSACCIONES_FINANCIERAS_PAGOS_CAPITAL primary key,
    id_fdu_transacciones_financiera number(10,0)
                                   constraint FK_FDU_TRANSACCIONES_FINANCIERAS_PAGOS_CAPITAL
                                   references FDU_TRANSACCIONES_FINANCIERAS on delete cascade not null,
    codigo_moneda                  number(5,0) not null,
    tasa_moneda                    number(20,5) not null,
    monto_origen                   number(20,5) not null,
    monto_local                    number(20,5) not null,
    mes                            number(5,0) not null,
    anio                           varchar2(6 char) not null,
    tipo_pago                      number(5,0) not null,
    estado                         number(5,0),
    usuario_grabacion              number(10,0) not null,
    fecha_grabacion                date default SYSDATE
)
;

-- table index
create index FK_FDU_TRANSACCIONES_FINANCIERAS_PAGOS_CAPITAL on SAF.FDU_TRANSACCIONES_FINANCIERAS_PAGOS_CAPITAL (id_fdu_transacciones_financier);

-- load data
 
-- Generated by Quick SQL Friday September 01, 2023  09:49:08
 
/*
FDU_TRANSACCIONES_FINANCIERAS_PAGOS_CAPITAL {
    id /pk,
    id_fdu_transacciones_financieras num(10,0) /nn /fk table FDU_TRANSACCIONES_FINANCIERAS
    codigo_moneda num(5,0) /nn,
    tasa_moneda num(20,5) /nn,
    monto_origen num(20,5) /nn,
    monto_local num(20,5) /nn,
    mes num(5,0) /nn,
    anio vc6 /nn,
    tipo_pago num(5,0) /nn,
    usuario_grabacion num(10,0) /nn,
    fecha_grabacion date /default sysdate
}

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
