-- SAF.FDU_OBJECT_CUADRO_ORIGEN_USO_FONDO definition

CREATE OR REPLACE TYPE SAF.FDU_OBJECT_CUADRO_ORIGEN_USO_FONDO AS OBJECT 
(
    CODIGO_EMPRESA NUMBER(10,0),
    NUMERO_CUENTA NUMBER(10,0),
    DESCRIPCION VARCHAR2(1024),
    INGRESOS NUMBER(28,5),
    EGRESOS NUMBER(28,5),
    VARIACION NUMBER(28,5),
    TIPO_RENGLON VARCHAR2(100),
    CLASE VARCHAR2(500),
    ORDEN NUMBER(10),
    ID NUMBER(10,0),
    ID_PADRE NUMBER(10,0)
);