-- create tables
create table SAF.FDU_TRANSACCIONES_FINANCIERAS_ESTADOS_LOG (
    id                             number generated by default on null as identity 
                                   constraint PK_FDU_TRANSACCIONES_FINANCIERAS_ESTADOS_LOG primary key,
    id_fdu_transacciones_financieras number(10,0)
                                   constraint FK_FDU_TRANSACCIONES_FINANCIERAS_ESTADOS_LOG
                                   references FDU_TRANSACCIONES_FINANCIERAS on delete cascade not null,
    estado                         varchar2(100 char) not null,
    observacion                    varchar2(2048 char),
    usuario_aceptacion             number(10,0) not null,
    fecha_aceptacion               date default SYSDATE
)
;

-- table index
create index FK_FDU_TRANSACCIONES_FINANCIERAS_ESTADOS_LOG on SAF.FDU_TRANSACCIONES_FINANCIERAS_ESTADOS_LOG (id_fdu_transacciones_financieras);

-- load data
 
-- Generated by Quick SQL Friday September 01, 2023  09:32:24
 
/*
FDU_TRANSACCIONES_FINANCIERAS_ESTADOS_LOG {
    id /pk,
    id_fdu_transacciones_financieras num(10,0) /nn /fk table FDU_TRANSACCIONES_FINANCIERAS
    estado vc100 /nn,
    observacion vc2048,
    usuario_aceptacion num(10,0) /nn,
    fecha_aceptacion date /default sysdate
}

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
