-- create tables
create table SAF.FDU_TRANSACCIONES_FINANCIERAS_PAGOS_DETALLE (
    id                             number generated by default on null as identity 
                                   constraint PK_FDU_TRANSACCIONES_FINANCIERAS_PAGOS_DETALLE primary key,
    id_fdu_transacciones_financiera number(10,0)
                                   constraint FK_FDU_TRANSACCIONES_FINANCIERAS_PAGOS_DETALLE
                                   references FDU_TRANSACCIONES_FINANCIERAS_PAGOS on delete cascade not null,
    rubro_cobro                    varchar2(100 char) not null,
    id_asociacion                  number(10,0) not null,
    mes                            number(5,0) not null,
    anio                           varchar2(6 char) not null,
    ID_PAGO                        number(10,0),
    usuario_grabacion              number(10,0) not null,
    fecha_grabacion                date default SYSDATE,
    usuario_modificacion           number(10,0),
    fecha_modificacion             date
)
;
-- table index
create index FDU_TRANSACCIONES_FINANCIERAS_PAGOS_DETALLE_FK on SAF.FDU_TRANSACCIONES_FINANCIERAS_PAGOS_DETALLE (id_fdu_transacciones_financiera);

-- load data
 
-- Generated by Quick SQL Friday September 01, 2023  09:56:56
 
/*
FDU_TRANSACCIONES_FINANCIERAS_PAGOS_DETALLE {
    id /pk,
    id_fdu_transacciones_financieras num(10,0) /nn /fk table FDU_TRANSACCIONES_FINANCIERAS_PAGOS,
    rubro_cobro vc100 /nn,
    id_asociacion num(10,0) /nn,
    mes num(5,0) /nn,
    anio vc6 /nn,
    usuario_grabacion num(10,0) /nn,
    fecha_grabacion date /default sysdate,
    usuario_modificacion num(10,0),
    fecha_modificacion date
}

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
