-- create tables
create table SAF.FDU_TRANSACCIONES_FINANCIERAS_PERMISOS_ESTADOS (
    id                             number generated by default on null as identity 
                                   constraint PK_FDU_TRANSACCIONES_FINANCIERAS_PERMISOS_ESTADOS primary key,
    estados                        varchar2(100 char) not null,
    usuario_encargado              number(10,0) not null,
    usuario_grabacion              number(10,0) not null,
    fecha_grabacion                date default SYSDATE,
    usuario_modificacion           number(10,0),
    fecha_modificacion             date
)
;

-- load data
 
-- Generated by Quick SQL Friday September 01, 2023  09:28:32
 
/*
FDU_TRANSACCIONES_FINANCIERAS_PERMISOS_ESTADOS {
    id /pk,
    estados vc100 /nn,
    usuario_encargado num(10,0) /nn,
    usuario_grabacion num(10,0) /nn,
    fecha_grabacion date /default sysdate,
    usuario_modificacion num(10,0),
    fecha_modificacion date
}

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
