-- create tables
create table SAF.FDU_TRANSACCIONES_FINANCIERAS (
    id                             number generated by default on null as identity 
                                   constraint fdu_transacciones_id_pk primary key,
    codigo_empresa                 number(3,0),
    tipo_destinatario              varchar2(10 char),
    id_asociacion                  number(10,0),
    estado                         varchar2(100 char),
    fecha_recuperacion_total       date,
    codigo_moneda                  number(5,0),
    tasa_cambio                    number(20,5),
    monto_origen                   number(20,5),
    monto_local                    number(20,5),
    observaciones                  varchar2(2048 char),
    es_prestamo                    varchar2(1 char) default 'N',
    tipo_prestamo                  number(3,0),
    plazo                          number(8,0),
    medida_plazo                   number(3,0),
    tipo_tasa                      number(5,0),
    tasa_interes                   number(20,5),
    fecha_cobro                    date,
    tipo_cobro_mora                number(5,0),
    tipo_mora                      number(5,0),
    porcentaje_mora                number(20,5),
    monto_mora_local               number(20,5),
    monto_mora_origen              number(20,5),
    monto_recuperado_local         number(20,5),
    monto_recuperado_origen        number(20,5),
    usuario_grabacion              number(10,0),
    fecha_grabacion                date default SYSDATE,
    usuario_modificacion           number(10,0),
    fecha_modificacion             date
)
;

-- table index
create index fdu_transacciones_i1 on SAF.FDU_TRANSACCIONES_FINANCIERAS (codigo_empresa);
create index fdu_transacciones_i22 on SAF.FDU_TRANSACCIONES_FINANCIERAS (tipo_destinatario);

-- load data
 
-- Generated by Quick SQL Friday September 01, 2023  09:27:55
 
/*
FDU_TRANSACCIONES_FINANCIERAS {
    id /pk,
    codigo_empresa num(3,0) /index,
    tipo_destinatario vc10 /index,
    id_asociacion num(10,0),
    estado vc100,
    fecha_recuperacion_total date,
    codigo_moneda num(5,0),
    tasa_cambio num(20,0),
    monto_origen num(20,0),
    monto_local num(20,0),
    observaciones vc2048,
    es_prestamo vc1 /default N
    tipo_prestamo num(3,0),
    plazo num(8,0),
    medida_plazo num(3,0),
    tipo_tasa num(5,0),
    tasa_interes num(20,5),
    fecha_cobro date,
    tipo_cobro_mora num(5,0),
    tipo_mora num(5,0),
    porcentaje_mora num(20,5),
    monto_mora_local num(20,5),
    monto_mora_origen num(20,5),
    monto_recuperado_local num(20,5),
    monto_recuperado_origen num(20,5),
    usuario_grabacion num(10,0),
    fecha_grabacion date /default sysdate,
    usuario_modificacion num(10,0),
    fecha_modificacion date
}

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
