-- SAF.FDU_OBJ_DETALLE_INTERES definition

CREATE OR REPLACE TYPE SAF.FDU_OBJ_DETALLE_INTERES AS OBJECT 
(
  FECHA_INTERES DATE,
  MONTO_ORIGEN NUMBER(20,5),
  MONTO_LOCAL NUMBER(20,5),
  CAPITAL NUMBER(20,5)
);