-- create tables
create table SAF.FDU_TRANSACCIONES_FINANCIERAS_PAGOS (
    id                             number generated by default on null as identity 
                                   constraint PK_FDU_TRANSACCIONES_FINANCIERAS_PAGOS primary key,
    id_fdu_transacciones_financieras number(10,0)
                                   constraint FK_FDU_TRANSACCIONES_FINANCIERAS_PAGOS
                                   references FDU_TRANSACCIONES_FINANCIERAS on delete cascade not null,
    codigo_moneda                  number(5,0),
    tasa_moneda                    number(20,5),
    monto_origen                   number(20,5),
    monto_local                    number(20,5),
    fecha_documento                date,
    numdoc                         number(8,0),
    codmae                         number(4,0),
    tipo_transaccion               number(10,0),
    serie                          varchar2(3 char),
    nrosolche                      number(8,0),
    id_cuenta                      number(10,0),
    codigo_operacion               number(3,0),
    concepto                       varchar2(2048 char),
    anulado                        varchar2(1 char),
    usuario_grabacion              number(10,0) not null,
    fecha_grabacion                date default SYSDATE,
    usuario_modificacion           number(10,0),
    fecha_modificacion             date
)
;

-- table index
create index FDU_TRANSACCIONES_FINANCIERAS_PAGOS_FK on SAF.FDU_TRANSACCIONES_FINANCIERAS_PAGOS (id_fdu_transacciones_financieras);

-- load data
 
-- Generated by Quick SQL Friday September 01, 2023  09:54:56
 
/*
FDU_TRANSACCIONES_FINANCIERAS_PAGOS {
    id /pk,
    id_fdu_transacciones_financieras num(10,0) /nn /fk table FDU_TRANSACCIONES_FINANCIERAS,
    codigo_moneda num(5,0),
    tasa_moneda num(20,5),
    monto_origen num(20,5),
    monto_local num(20,5),
    fecha_documento date,
    numdoc num(8,0),
    codmae num(4,0),
    tipo_transaccion num(10,0),
    serie vc3,
    nrosolche num(8,0),
    id_cuenta num(10,0),
    codigo_operacion num(3,0),
    concepto vc2048,
    usuario_grabacion num(10,0) /nn,
    fecha_grabacion date /default sysdate,
    usuario_modificacion num(10,0),
    fecha_modificacion date
}

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
