create table SAF.FLUJO_EFECTIVO_FDU_TRANSACCIONES_FINANCIERAS (
    id                             number,
    codigo_empresa                 number(3,0),
    tipo_destinatario              varchar2(10 char),
    id_asociacion                  number(10,0),
    estado                         varchar2(100 char),
    fecha_recuperacion_total       date,
    codigo_moneda                  number(5,0),
    tasa_cambio                    number(20,5),
    monto_origen                   number(20,5),
    monto_local                    number(20,5),
    observaciones                  varchar2(2048 char),
    es_prestamo                    varchar2(1 char) default 'N',
    tipo_prestamo                  number(3,0),
    plazo                          number(8,0),
    medida_plazo                   number(3,0),
    tipo_tasa                      number(5,0),
    tasa_interes                   number(20,5),
    fecha_cobro                    date,
    tipo_cobro_mora                number(5,0),
    tipo_mora                      number(5,0),
    porcentaje_mora                number(20,5),
    monto_mora_local               number(20,5),
    monto_mora_origen              number(20,5),
    monto_recuperado_local         number(20,5),
    monto_recuperado_origen        number(20,5),
    usuario_grabacion              number(10,0),
    fecha_grabacion                date default SYSDATE,
    usuario_modificacion           number(10,0),
    fecha_modificacion             date,
    id_flujo                       number(10,0),
    codigo_presupuesto             varchar2(200 char),
    aplica_pago                    varchar2(1 char)
);