CREATE OR REPLACE FUNCTION SAF.GET_FDU_LISTA_DESTINATARIOS
(
	V_EMPRESA NUMBER,
    V_TIPO_DESTINATARIO VARCHAR2
)
RETURN FDU_T_LISTA_DESTINATARIO AS
    V_FDU_T_LISTA_DESTINATARIO FDU_T_LISTA_DESTINATARIO := FDU_T_LISTA_DESTINATARIO(); 

    CURSOR C_EMPRESAS IS
        SELECT 
            CODIGO_EMPRESA||' - '||NVL(NOMBRE_PERSONA,RAZON_SOCIAL) NOMBRE, 
            CODIGO_EMPRESA
        FROM GRAL_PERSONAS_TABLE E, GRAL_EMPRESAS P
        WHERE E.CODIGO_PERSONA = P.CODIGO_PERSONA
        AND P.CODIGO_ESTADO IN 
        (
            SELECT 
                CODIGO_ESTATUS
            FROM GRAL_ESTATUS_MODULOS
            WHERE CODIGO_MODULO = 1
            AND PERMITE_MOVTOS = 'S'
        )    
        AND P.CODIGO_EMPRESA > 99
        AND P.CODIGO_EMPRESA != V_EMPRESA
        ORDER BY P.CODIGO_EMPRESA;
    
    CURSOR C_PROVEEDORES IS
        SELECT
            SAF.FNC_NPROVEEDOR(CODIGO_PROVEEDOR) NOMBRE,
            CODIGO_PROVEEDOR
        FROM SAF.CXP_PROVEEDORES;

    CURSOR C_PROYECTOS IS
        SELECT
            (CODIGO_PROYECTO || ' - ' || DESCRIPCION) NOMBRE,
            ID
        FROM SAF.EST_PROYECTOS;
    
    CURSOR C_CLIENTES IS 
        SELECT 
            NOMBRE_FACTURAR,
            NUMERO_CUENTA
        FROM SAF.CXC_CUENTAS
        WHERE CODIGO_EMPRESA = V_EMPRESA
        AND CODIGO_ESTATUS = 1
        AND INTERCOMPANY = 'S'
        ORDER BY NUMERO_CUENTA ASC;
BEGIN
    IF V_TIPO_DESTINATARIO = 'EMPRESA' THEN
        FOR R_DATOS IN C_EMPRESAS
        LOOP
            V_FDU_T_LISTA_DESTINATARIO.EXTEND;
            V_FDU_T_LISTA_DESTINATARIO(V_FDU_T_LISTA_DESTINATARIO.LAST) := FDU_OBJ_LISTA_DESTINATARIO
            (
                R_DATOS.NOMBRE,
                R_DATOS.CODIGO_EMPRESA
            );
        END LOOP;
    ELSIF V_TIPO_DESTINATARIO = 'PROVEEDOR' THEN
        FOR R_DATOS IN C_PROVEEDORES
        LOOP
            V_FDU_T_LISTA_DESTINATARIO.EXTEND;
            V_FDU_T_LISTA_DESTINATARIO(V_FDU_T_LISTA_DESTINATARIO.LAST) := FDU_OBJ_LISTA_DESTINATARIO
            (
                R_DATOS.NOMBRE,
                R_DATOS.CODIGO_PROVEEDOR
            );
        END LOOP;
    ELSIF V_TIPO_DESTINATARIO = 'PROYECTO' THEN
        FOR R_DATOS IN C_PROYECTOS
        LOOP
            V_FDU_T_LISTA_DESTINATARIO.EXTEND;
            V_FDU_T_LISTA_DESTINATARIO(V_FDU_T_LISTA_DESTINATARIO.LAST) := FDU_OBJ_LISTA_DESTINATARIO
            (
                R_DATOS.NOMBRE,
                R_DATOS.ID
            );
        END LOOP;
    ELSIF V_TIPO_DESTINATARIO = 'CLIENTE' THEN
        FOR R_DATOS IN C_CLIENTES
        LOOP
            V_FDU_T_LISTA_DESTINATARIO.EXTEND;
            V_FDU_T_LISTA_DESTINATARIO(V_FDU_T_LISTA_DESTINATARIO.LAST) := FDU_OBJ_LISTA_DESTINATARIO
            (
                R_DATOS.NOMBRE_FACTURAR,
                R_DATOS.NUMERO_CUENTA
            );
        END LOOP;
    END IF;
	
    RETURN V_FDU_T_LISTA_DESTINATARIO;
END GET_FDU_LISTA_DESTINATARIOS;