CREATE OR REPLACE FUNCTION SAF.GET_FDU_NOMBRE_DESTINATARIO
(
	V_ID_ASOCIACION NUMBER,
    V_EMPRESA NUMBER,
    V_TIPO_DESTINATARIO VARCHAR2
)
RETURN VARCHAR2 AS
    V_NOMBRE VARCHAR2(200); 

BEGIN
    IF 
	    V_TIPO_DESTINATARIO = 'EMPRESA' THEN
	        V_NOMBRE := SAF.FN_NOMBRE_EMPRESA(V_ID_ASOCIACION);
	    ELSIF V_TIPO_DESTINATARIO = 'PROVEEDOR' THEN
	        V_NOMBRE := SAF.FNCPRS_NOMBRE_PROVEEDOR(V_ID_ASOCIACION);
	    ELSIF V_TIPO_DESTINATARIO = 'PROYECTO' THEN
	        SELECT
	            DESCRIPCION
	            INTO
	            V_NOMBRE
	        FROM SAF.EST_PROYECTOS
	        WHERE ID = V_ID_ASOCIACION;
	    ELSIF V_TIPO_DESTINATARIO = 'CLIENTE' THEN
	        V_NOMBRE := SAF.FNC_GET_NOMBRE_CLIENTE(V_EMPRESA, V_ID_ASOCIACION);
    END IF;
	
    RETURN V_NOMBRE;
END GET_FDU_NOMBRE_DESTINATARIO;