CREATE OR REPLACE FUNCTION SAF.GET_CENTRO_COSTO_PADRE
(
	P_CODIGO_CC VARCHAR2
)
RETURN VARCHAR2 AS
	V_CODIGO VARCHAR2(100);

    CURSOR C_CODIGO_CC IS
        SELECT
            CODIGO_CC_PADRE
        FROM SAF.GRAL_CENTROS_COSTOS_TABLE 
        WHERE CODIGO_CC = P_CODIGO_CC;
BEGIN
    OPEN C_CODIGO_CC;
        FETCH C_CODIGO_CC INTO V_CODIGO;
    CLOSE C_CODIGO_CC;
    
    RETURN V_CODIGO;
END GET_CENTRO_COSTO_PADRE;