CREATE OR REPLACE FUNCTION SAF.GET_FDU_VALOR_VALIDADO_BOLETA
(
	V_ID_ASOCIACION NUMBER,
    V_ID_TRANSACCION NUMBER
)
RETURN NUMBER AS
    V_VALOR NUMBER; 

BEGIN
    SELECT
        (NVL(A.MONTO_ORIGEN, 0) + NVL(C.MONTO_ORIGEN, 0) + NVL(D.MONTO_ORIGEN, 0))
    INTO
        V_VALOR
    FROM SAF.FDU_TRANSACCIONES_FINANCIERAS_INTERES_COBRADOS A
    INNER JOIN SAF.FDU_TRANSACCIONES_FINANCIERAS B
        ON B.ID = A.ID_FDU_TRANSACCIONES_FINANCIERAS
    LEFT JOIN SAF.FDU_TRANSACCIONES_FINANCIERAS_PAGOS_CAPITAL C
        ON C.ID_FDU_TRANSACCIONES_FINANCIERA = A.ID_FDU_TRANSACCIONES_FINANCIERAS
        AND C.MES = A.MES
        AND C.ANIO = A.ANIO
        AND C.TIPO_PAGO = 1
    LEFT JOIN SAF.FDU_TRANSACCIONES_FINANCIERAS_MORAS D
        ON D.ID_FDU_TRANSACCIONES_FINANCIERAS = A.ID_FDU_TRANSACCIONES_FINANCIERAS
        AND D.MES = A.MES
        AND D.ANIO = A.ANIO
        AND D.MONTO_ORIGEN > 0
    INNER JOIN SAF.GRAL_MONEDAS E
        ON B.CODIGO_MONEDA = E.CODIGO_MONEDA
    WHERE A.ID_FDU_TRANSACCIONES_FINANCIERAS = V_ID_TRANSACCION
    AND A.ID IN 
    (
        SELECT
            F.ID_ASOCIACION
        FROM SAF.FDU_TRANSACCIONES_FINANCIERAS_PAGOS E
        INNER JOIN SAF.FDU_TRANSACCIONES_FINANCIERAS_PAGOS_DETALLE F
            ON F.ID_FDU_TRANSACCIONES_FINANCIERA = E.ID
            AND F.RUBRO_COBRO = 'INTERES'
        WHERE E.ID_FDU_TRANSACCIONES_FINANCIERAS = A.ID_FDU_TRANSACCIONES_FINANCIERAS
        AND E.ID = V_ID_ASOCIACION
    );
	
    RETURN V_VALOR;
END GET_FDU_VALOR_VALIDADO_BOLETA;