CREATE OR REPLACE FUNCTION SAF.GET_FDU_PERMISO_REGISTRO
(
	V_ID NUMBER,
    V_CODIGO_USUARIO NUMBER
)
RETURN NUMBER AS
    V_PERMISO NUMBER;
    V_ESTADO VARCHAR2(100);
    V_USUARIO NUMBER;

    V_P_REVISION NUMBER;
BEGIN
    SELECT
        ESTADO,
        USUARIO_GRABACION
        INTO
        V_ESTADO,
        V_USUARIO
    FROM SAF.FDU_TRANSACCIONES_FINANCIERAS
    WHERE ID = V_ID;

    IF (V_ESTADO = 'RECHAZADO' OR V_ESTADO = 'ACEPTADO' OR V_ESTADO = 'CANCELADO') THEN
        V_PERMISO := 2;
    ELSIF (V_ESTADO = 'SOLICITUD' AND V_USUARIO = V_CODIGO_USUARIO) THEN
        V_PERMISO := 1;
    ELSIF V_ESTADO = 'ENVIADO A REVISION' THEN
        SELECT
            COUNT(*) 
            INTO
            V_P_REVISION
        FROM SAF.FDU_TRANSACCIONES_FINANCIERAS_PERMISOS_ESTADOS
        WHERE ESTADOS = 'REVISION'
        AND USUARIO_ENCARGADO = V_CODIGO_USUARIO;

        IF V_P_REVISION != 0 THEN
            V_PERMISO := 1;
        ELSE
            V_PERMISO := 0;
        END IF;
    ELSIF V_ESTADO = 'PENDIENTE APROBACION' THEN
        SELECT
            COUNT(*) 
            INTO
            V_P_REVISION
        FROM SAF.FDU_TRANSACCIONES_FINANCIERAS_PERMISOS_ESTADOS
        WHERE ESTADOS = 'APROBACION'
        AND USUARIO_ENCARGADO = V_CODIGO_USUARIO;

        IF V_P_REVISION != 0 THEN
            V_PERMISO := 1;
        ELSE
            V_PERMISO := 0;
        END IF;
    ELSIF V_ESTADO = 'REVISION' THEN
        DECLARE
            CURSOR C_USUARIO IS
                SELECT 
                    A.USUARIO_ACEPTACION
                FROM SAF.FDU_TRANSACCIONES_FINANCIERAS_ESTADOS_LOG A
                WHERE A.ID_FDU_TRANSACCIONES_FINANCIERAS = V_ID
                AND A.ID =
                (
                    SELECT MAX(B.ID) FROM SAF.FDU_TRANSACCIONES_FINANCIERAS_ESTADOS_LOG B WHERE B.ID_FDU_TRANSACCIONES_FINANCIERAS = A.ID_FDU_TRANSACCIONES_FINANCIERAS
                )
                AND A.ESTADO = 'REVISION';
        BEGIN
            V_USUARIO := NULL;

            OPEN C_USUARIO;
                FETCH C_USUARIO INTO V_USUARIO;
            CLOSE C_USUARIO;

            IF V_CODIGO_USUARIO = V_USUARIO THEN
                V_PERMISO := 1;
            ELSE
                V_PERMISO := 0;
            END IF;
        END;
    ELSIF V_ESTADO = 'APROBACION' THEN
        DECLARE
            CURSOR C_USUARIO IS
                SELECT 
                    A.USUARIO_ACEPTACION
                FROM SAF.FDU_TRANSACCIONES_FINANCIERAS_ESTADOS_LOG A
                WHERE A.ID_FDU_TRANSACCIONES_FINANCIERAS = V_ID
                AND A.ID =
                (
                    SELECT MAX(B.ID) FROM SAF.FDU_TRANSACCIONES_FINANCIERAS_ESTADOS_LOG B WHERE B.ID_FDU_TRANSACCIONES_FINANCIERAS = A.ID_FDU_TRANSACCIONES_FINANCIERAS
                )
                AND A.ESTADO = 'APROBACION';
        BEGIN
            V_USUARIO := NULL;

            OPEN C_USUARIO;
                FETCH C_USUARIO INTO V_USUARIO;
            CLOSE C_USUARIO;

            IF V_CODIGO_USUARIO = V_USUARIO THEN
                V_PERMISO := 1;
            ELSE
                V_PERMISO := 0;
            END IF;
        END;
    ELSE
        V_PERMISO := 0;
    END IF;
	
    RETURN V_PERMISO;
END GET_FDU_PERMISO_REGISTRO;