CREATE OR REPLACE PROCEDURE SAF.PR_FLUJO_TRANSACCIONES_FINANCIERAS(
  P_ID_FLUJO        FLUJO_EFECTIVO_PROCESO.id%TYPE DEFAULT 0,
  P_EMPRESA         GRAL_EMPRESAS.CODIGO_EMPRESA%TYPE DEFAULT NULL
) IS
BEGIN
    DELETE FROM SAF.FLUJO_EFECTIVO_FDU_TRANSACCIONES_FINANCIERAS
    WHERE ID_FLUJO = P_ID_FLUJO
    AND CODIGO_EMPRESA IN
    (
        SELECT 
            CODIGO_EMPRESA 
        FROM SAF.FLUJO_EMPRESAS_CONSOLIDADORAS
        WHERE CODIGO_EMPRESA_CONSOLIDADORA  = NVL(P_EMPRESA, CODIGO_EMPRESA_CONSOLIDADORA)
    );
    COMMIT;

    INSERT INTO SAF.FLUJO_EFECTIVO_FDU_TRANSACCIONES_FINANCIERAS
    (
        ID,
        CODIGO_EMPRESA,
        TIPO_DESTINATARIO,
        ID_ASOCIACION,
        ESTADO,
        FECHA_RECUPERACION_TOTAL,
        CODIGO_MONEDA,
        TASA_CAMBIO,
        MONTO_ORIGEN,
        MONTO_LOCAL,
        OBSERVACIONES,
        ES_PRESTAMO,
        TIPO_PRESTAMO,
        PLAZO,
        MEDIDA_PLAZO,
        TIPO_TASA,
        TASA_INTERES,
        FECHA_COBRO,
        TIPO_COBRO_MORA,
        TIPO_MORA,
        PORCENTAJE_MORA,
        MONTO_MORA_LOCAL,
        MONTO_MORA_ORIGEN,
        MONTO_RECUPERADO_LOCAL,
        MONTO_RECUPERADO_ORIGEN,
        USUARIO_GRABACION,
        FECHA_GRABACION,
        USUARIO_MODIFICACION,
        FECHA_MODIFICACION,
        ID_FLUJO
    )
    SELECT 
        A.ID,
        A.CODIGO_EMPRESA,
        A.TIPO_DESTINATARIO,
        A.ID_ASOCIACION,
        A.ESTADO,
        A.FECHA_RECUPERACION_TOTAL,
        A.CODIGO_MONEDA,
        A.TASA_CAMBIO,
        A.MONTO_ORIGEN,
        A.MONTO_LOCAL,
        A.OBSERVACIONES,
        A.ES_PRESTAMO,
        A.TIPO_PRESTAMO,
        A.PLAZO,
        A.MEDIDA_PLAZO,
        A.TIPO_TASA,
        A.TASA_INTERES,
        A.FECHA_COBRO,
        A.TIPO_COBRO_MORA,
        A.TIPO_MORA,
        A.PORCENTAJE_MORA,
        A.MONTO_MORA_LOCAL,
        A.MONTO_MORA_ORIGEN,
        A.MONTO_RECUPERADO_LOCAL,
        A.MONTO_RECUPERADO_ORIGEN,
        A.USUARIO_GRABACION,
        A.FECHA_GRABACION,
        A.USUARIO_MODIFICACION,
        A.FECHA_MODIFICACION,
        P_ID_FLUJO
    FROM SAF.FDU_TRANSACCIONES_FINANCIERAS A
    WHERE A.ESTADO = 'LIBERACION';
END;