create or replace FUNCTION     GET_GENERADOR_CODIGOS_RENGLONES_ORDENES_CAMBIO
(
    V_ID_CONTRATO NUMBER,
    V_CODIGO_RENGLON_PADRE VARCHAR2 DEFAULT NULL,
    V_TIPO_RENGLON NUMBER,
    V_TIPO_CODIGO NUMBER DEFAULT 1,
    V_ID_ORDEN_CAMBIO ORDENES_CAMBIO.ID%TYPE
)
    RETURN VARCHAR2 AS

    CURSOR C_CODIGO_NUMERICO_RENGLON(P_ID_CONTRATO NUMBER) IS
        SELECT
            NVL(MAX(TO_NUMBER(CODIGO_RENGLON)), 0) + 1
        FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES A
        WHERE A.ID_ORDEN_CAMBIO = V_ID_ORDEN_CAMBIO
          AND A.ID_CONTRATO = P_ID_CONTRATO
          AND A.ES_PADRE = 1
          AND A.CODIGO_RENGLON_PADRE IS NULL;


    CURSOR C_CODIGO_NUMERICO_SERVICIO(P_ID_CONTRATO NUMBER, P_CODIGO_RENGLON_PADRE VARCHAR2) IS
        WITH CORRELATIVO AS
                 (
                     SELECT
                         TO_NUMBER(REPLACE(CODIGO_RENGLON, P_CODIGO_RENGLON_PADRE || '.', '')) CODIGOS
                     FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES A
                     WHERE A.ID_ORDEN_CAMBIO = V_ID_ORDEN_CAMBIO
                       AND A.ID_CONTRATO = P_ID_CONTRATO
                       AND A.ES_PADRE = 1
                       AND A.CODIGO_RENGLON_PADRE = P_CODIGO_RENGLON_PADRE
                 )
        SELECT
            NVL(MAX(CODIGOS), 0) + 1
        FROM CORRELATIVO;

    CURSOR C_RENGLON_PADRE(P_CONTRATOID NUMBER, P_ORDEN_CAMBIO NUMBER) IS
        SELECT
            LPAD(MAX(NVL(TO_NUMBER(CODIGO_RENGLON), 0)) + 1,2,'0') AS CODIGO_RENGLON
        FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
        WHERE ID_CONTRATO = P_CONTRATOID
          AND ID_ORDEN_CAMBIO = P_ORDEN_CAMBIO
          AND ES_PADRE = 1
          AND CODIGO_RENGLON_PADRE IS NULL;

    CURSOR C_RENGLON_PADRE_HIJOS(P_CONTRATOID NUMBER, P_ORDEN_CAMBIO NUMBER, P_CODIGO_PADRE VARCHAR2) IS
        SELECT
            LPAD(MAX(NVL(TO_NUMBER(CODIGO_RENGLON), 0)) + 1,2,'0') AS CODIGO_RENGLON
        FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
        WHERE ID_CONTRATO = P_CONTRATOID
          AND ID_ORDEN_CAMBIO = P_ORDEN_CAMBIO
          AND ES_PADRE = 1
          AND CODIGO_RENGLON_PADRE = P_CODIGO_PADRE;

    V_CODIGO NUMBER;
    V_CONTADOR VARCHAR2(1024);
BEGIN
    IF V_TIPO_CODIGO = 1 THEN
        IF V_TIPO_RENGLON = 1 THEN
            OPEN C_CODIGO_NUMERICO_RENGLON(V_ID_CONTRATO);
            FETCH C_CODIGO_NUMERICO_RENGLON INTO V_CODIGO;
            CLOSE C_CODIGO_NUMERICO_RENGLON;

            V_CONTADOR := LPAD(V_CODIGO,2,'0');
        ELSIF V_TIPO_RENGLON = 2 THEN
            OPEN C_CODIGO_NUMERICO_SERVICIO(V_ID_CONTRATO, V_CODIGO_RENGLON_PADRE);
            FETCH C_CODIGO_NUMERICO_SERVICIO INTO V_CODIGO;
            CLOSE C_CODIGO_NUMERICO_SERVICIO;
            V_CONTADOR := V_CODIGO_RENGLON_PADRE || '.' || LPAD(V_CODIGO,2,'0');
        ELSE
            NULL;
        END IF;
        /*IF V_CODIGO_RENGLON_PADRE IS NULL THEN
            OPEN C_RENGLON_PADRE(V_ID_CONTRATO, V_ID_ORDEN_CAMBIO);
                FETCH C_RENGLON_PADRE INTO V_CONTADOR;
            CLOSE C_RENGLON_PADRE;
        ELSE
            OPEN C_RENGLON_PADRE_HIJOS(V_ID_CONTRATO, V_ID_ORDEN_CAMBIO, V_CODIGO_RENGLON_PADRE);
                FETCH C_RENGLON_PADRE_HIJOS INTO V_CONTADOR;
            CLOSE C_RENGLON_PADRE_HIJOS;
        END IF;*/
    ELSE
        NULL;
    END IF;

    RETURN V_CONTADOR;
END;