CREATE OR REPLACE PROCEDURE SAF.OC_CAMBIO_ARRIBA
(
    V_CS_COTRATOID NUMBER,
    v_ID_RENGLON NUMBER,
    V_TIPO_CODIGO NUMBER,
    V_ORDEN_CAMBIO NUMBER
) AS
    CURSOR C_RENGLON_SUPERIOR(P_CONTRATOID NUMBER, P_RENGLON NUMBER, P_ORDEN_CAMBIO NUMBER) IS
        WITH DATOS_RENGLON AS
            (SELECT
                ID,
                CODIGO_RENGLON,
                CODIGO_RENGLON_PADRE,
                ORDEN,
                LEVEL AS NIVEL
            FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
            WHERE ID_ORDEN_CAMBIO = P_ORDEN_CAMBIO
              AND ES_PADRE = 1
            START WITH CODIGO_RENGLON_PADRE IS NULL
            CONNECT BY PRIOR CODIGO_RENGLON = CODIGO_RENGLON_PADRE),
            DATOS AS
            (SELECT
                 B.ID,
                 B.CODIGO_RENGLON,
                 B.ORDEN
            FROM DATOS_RENGLON A
            INNER JOIN DATOS_RENGLON B
                ON B.NIVEL = A.NIVEL
                AND TO_NUMBER(B.ORDEN) < TO_NUMBER(A.ORDEN)
            WHERE A.ID = P_RENGLON)
            SELECT
                A.ID,
                A.CODIGO_RENGLON
            FROM DATOS A
            WHERE TO_NUMBER(A.ORDEN) = (SELECT MAX(TO_NUMBER(B.ORDEN)) FROM DATOS B);

    CURSOR C_RENGLON_INFERIOR(P_CONTRATOID NUMBER, P_RENGLON NUMBER) IS
        SELECT
            CODIGO_RENGLON
        FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
        WHERE ID = P_RENGLON;

    CURSOR C_UPDATE_CODIGOS_LIKE (P_CONTRATOID NUMBER, P_RENGLON VARCHAR2, P_ORDEN_CAMBIO NUMBER) IS
        SELECT
            ID,
            CODIGO_RENGLON
        FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
        WHERE ID_ORDEN_CAMBIO = P_ORDEN_CAMBIO
          AND CODIGO_RENGLON LIKE P_RENGLON || '.%';

    CURSOR C_UPDATE_CODIGOS (P_CONTRATOID NUMBER, P_RENGLON VARCHAR2, P_ORDEN_CAMBIO NUMBER) IS
        SELECT
            ID,
            CODIGO_RENGLON
        FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
        WHERE ID_ORDEN_CAMBIO = P_ORDEN_CAMBIO
          AND CODIGO_RENGLON = P_RENGLON;

    CURSOR C_UPDATE_PADRES_LIKE (P_CONTRATOID NUMBER, P_RENGLON VARCHAR2, P_ORDEN_CAMBIO NUMBER) IS
        SELECT
            ID,
            CODIGO_RENGLON_PADRE
        FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
        WHERE ID_ORDEN_CAMBIO = P_ORDEN_CAMBIO
          AND CODIGO_RENGLON_PADRE LIKE P_RENGLON || '.%';

    CURSOR C_UPDATE_PADRES (P_CONTRATOID NUMBER, P_RENGLON VARCHAR2, P_ORDEN_CAMBIO NUMBER) IS
        SELECT
            ID,
            CODIGO_RENGLON_PADRE
        FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
        WHERE ID_ORDEN_CAMBIO = P_ORDEN_CAMBIO
          AND CODIGO_RENGLON_PADRE = P_RENGLON;

    V_CODIGO_SUPERIOR VARCHAR2(1024);
    V_CODIGO_INFERIOR VARCHAR2(1024);
    V_TEMP_CODIGO VARCHAR2(1024);
BEGIN
    IF V_TIPO_CODIGO = 1 THEN
        FOR R_RENGLON_SUPERIOR IN C_RENGLON_SUPERIOR(V_CS_COTRATOID, v_ID_RENGLON, V_ORDEN_CAMBIO)
            LOOP
                OPEN C_RENGLON_INFERIOR(V_CS_COTRATOID, v_ID_RENGLON);
                FETCH C_RENGLON_INFERIOR INTO V_CODIGO_INFERIOR;
                CLOSE C_RENGLON_INFERIOR;

                V_CODIGO_SUPERIOR := R_RENGLON_SUPERIOR.CODIGO_RENGLON;

                -- RENGLON TEMPORAL
                FOR R_TEMP IN C_UPDATE_CODIGOS_LIKE(V_CS_COTRATOID, R_RENGLON_SUPERIOR.CODIGO_RENGLON, V_ORDEN_CAMBIO)
                    LOOP
                        UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
                        SET CODIGO_RENGLON = 'TEMP.' || SUBSTR(R_TEMP.CODIGO_RENGLON, LENGTH(R_RENGLON_SUPERIOR.CODIGO_RENGLON || '.') + 1)
                        WHERE ID = R_TEMP.ID;
                    END LOOP;

                FOR R_TEMP IN C_UPDATE_CODIGOS(V_CS_COTRATOID, R_RENGLON_SUPERIOR.CODIGO_RENGLON, V_ORDEN_CAMBIO)
                    LOOP
                        UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
                        SET CODIGO_RENGLON = 'TEMP'
                        WHERE ID = R_TEMP.ID;
                    END LOOP;

                FOR R_TEMP IN C_UPDATE_PADRES_LIKE(V_CS_COTRATOID, R_RENGLON_SUPERIOR.CODIGO_RENGLON, V_ORDEN_CAMBIO)
                    LOOP
                        UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
                        SET CODIGO_RENGLON_PADRE = 'TEMP.' || SUBSTR(R_TEMP.CODIGO_RENGLON_PADRE, LENGTH(R_RENGLON_SUPERIOR.CODIGO_RENGLON || '.') + 1)
                        WHERE ID = R_TEMP.ID;
                    END LOOP;

                FOR R_TEMP IN C_UPDATE_PADRES(V_CS_COTRATOID, R_RENGLON_SUPERIOR.CODIGO_RENGLON, V_ORDEN_CAMBIO)
                    LOOP
                        UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
                        SET CODIGO_RENGLON_PADRE = 'TEMP'
                        WHERE ID = R_TEMP.ID;
                    END LOOP;

                -- RENGLON INFERIOR
                FOR R_TEMP IN C_UPDATE_CODIGOS_LIKE(V_CS_COTRATOID, V_CODIGO_INFERIOR, V_ORDEN_CAMBIO)
                    LOOP
                        V_TEMP_CODIGO := V_CODIGO_SUPERIOR || '.' || SUBSTR(R_TEMP.CODIGO_RENGLON, LENGTH(V_CODIGO_INFERIOR || '.') + 1);
                        UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
                        SET CODIGO_RENGLON = V_TEMP_CODIGO,
                            ORDEN = SUBSTR(V_TEMP_CODIGO, INSTR(V_TEMP_CODIGO, '.', -1) + 1)
                        WHERE ID = R_TEMP.ID;
                    END LOOP;

                FOR R_TEMP IN C_UPDATE_CODIGOS(V_CS_COTRATOID, V_CODIGO_INFERIOR, V_ORDEN_CAMBIO)
                    LOOP
                        UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
                        SET CODIGO_RENGLON = V_CODIGO_SUPERIOR,
                            ORDEN = SUBSTR(V_CODIGO_SUPERIOR, INSTR(V_CODIGO_SUPERIOR, '.', -1) + 1)
                        WHERE ID = R_TEMP.ID;
                    END LOOP;

                FOR R_TEMP IN C_UPDATE_PADRES_LIKE(V_CS_COTRATOID, V_CODIGO_INFERIOR, V_ORDEN_CAMBIO)
                    LOOP
                        V_TEMP_CODIGO := V_CODIGO_SUPERIOR || '.' || SUBSTR(R_TEMP.CODIGO_RENGLON_PADRE, LENGTH(V_CODIGO_INFERIOR || '.') + 1);
                        UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
                        SET CODIGO_RENGLON_PADRE = V_TEMP_CODIGO,
                            ORDEN = SUBSTR(V_TEMP_CODIGO, INSTR(V_TEMP_CODIGO, '.', -1) + 1)
                        WHERE ID = R_TEMP.ID;
                    END LOOP;

                FOR R_TEMP IN C_UPDATE_PADRES(V_CS_COTRATOID, V_CODIGO_INFERIOR, V_ORDEN_CAMBIO)
                    LOOP
                        UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
                        SET CODIGO_RENGLON_PADRE = V_CODIGO_SUPERIOR,
                            ORDEN = SUBSTR(V_CODIGO_SUPERIOR, INSTR(V_CODIGO_SUPERIOR, '.', -1) + 1)
                        WHERE ID = R_TEMP.ID;
                    END LOOP;

                -- RENGLON SUPERIOR TEMP
                FOR R_TEMP IN C_UPDATE_CODIGOS_LIKE(V_CS_COTRATOID, 'TEMP', V_ORDEN_CAMBIO)
                    LOOP
                        V_TEMP_CODIGO := V_CODIGO_INFERIOR || '.' || SUBSTR(R_TEMP.CODIGO_RENGLON, LENGTH('TEMP.') + 1);
                        UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
                        SET CODIGO_RENGLON = V_TEMP_CODIGO,
                            ORDEN = SUBSTR(V_TEMP_CODIGO, INSTR(V_TEMP_CODIGO, '.', -1) + 1)
                        WHERE ID = R_TEMP.ID;
                    END LOOP;

                FOR R_TEMP IN C_UPDATE_CODIGOS(V_CS_COTRATOID, 'TEMP', V_ORDEN_CAMBIO)
                    LOOP
                        UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
                        SET CODIGO_RENGLON = V_CODIGO_INFERIOR,
                            ORDEN = SUBSTR(V_CODIGO_INFERIOR, INSTR(V_CODIGO_INFERIOR, '.', -1) + 1)
                        WHERE ID = R_TEMP.ID;
                    END LOOP;

                FOR R_TEMP IN C_UPDATE_PADRES_LIKE(V_CS_COTRATOID, 'TEMP', V_ORDEN_CAMBIO)
                    LOOP
                        V_TEMP_CODIGO := V_CODIGO_INFERIOR || '.' || SUBSTR(R_TEMP.CODIGO_RENGLON_PADRE, LENGTH('TEMP.') + 1);
                        UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
                        SET CODIGO_RENGLON_PADRE = V_TEMP_CODIGO,
                            ORDEN = SUBSTR(V_TEMP_CODIGO, INSTR(V_TEMP_CODIGO, '.', -1) + 1)
                        WHERE ID = R_TEMP.ID;
                    END LOOP;

                FOR R_TEMP IN C_UPDATE_PADRES(V_CS_COTRATOID, 'TEMP', V_ORDEN_CAMBIO)
                    LOOP
                        UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
                        SET CODIGO_RENGLON_PADRE = V_CODIGO_INFERIOR,
                            ORDEN = SUBSTR(V_CODIGO_INFERIOR, INSTR(V_CODIGO_INFERIOR, '.', -1) + 1)
                        WHERE ID = R_TEMP.ID;
                    END LOOP;
            END LOOP;
    END IF;

    SAF.RENGLONES_ACTIVIDADES_ORDENES_CAMBIO_SUMARIZACION(V_ORDEN_CAMBIO,V_CS_COTRATOID,NULL,NULL,NULL);
END;