create or replace PROCEDURE     SAF.PR_CORRECCION_CODIGOS_ORDENES_CAMBIO(
    VID_ORDEN_CAMBIO ORDENES_CAMBIO.ID%TYPE,
    VID_CONTRATO EST_CONTRATOS.CODIGO_CONTRATO%TYPE,
    VCODIGO_RENGLON_PADRE VARCHAR2,
    VORDEN NUMBER
) AS
    CURSOR RENGLONES_ORDENES  IS
        SELECT
            LEVEL,
            ID,
            CODIGO_RENGLON,
            CODIGO_RENGLON_PADRE,
            NOMBRE
        FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES A
        WHERE A.ES_PADRE = 1
          AND A.ID_ORDEN_CAMBIO = VID_ORDEN_CAMBIO
          AND A.ID_CONTRATO = VID_CONTRATO
          AND LEVEL = 1
          AND A.ORDEN = VORDEN
        START WITH A.CODIGO_RENGLON_PADRE IS NULL
        CONNECT BY PRIOR A.CODIGO_RENGLON = A.CODIGO_RENGLON_PADRE
        ORDER SIBLINGS BY ORDEN;

    CURSOR RENGLONES_NIVEL_SEGUNDO IS
        SELECT
            LEVEL,
            ROW_NUMBER() OVER (ORDER BY ORDEN) NUMERO,
            ID,
            CODIGO_RENGLON,
            CODIGO_RENGLON_PADRE,
            NOMBRE
        FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES A
        WHERE A.ES_PADRE = 1
          AND A.ID_ORDEN_CAMBIO = VID_ORDEN_CAMBIO
          AND A.ID_CONTRATO = VID_CONTRATO
          AND LEVEL = 2
          AND A.ORDEN = VORDEN
          AND A.CODIGO_RENGLON_PADRE = VCODIGO_RENGLON_PADRE --'01'
        START WITH A.CODIGO_RENGLON_PADRE IS NULL
        CONNECT BY PRIOR A.CODIGO_RENGLON = A.CODIGO_RENGLON_PADRE;


    CURSOR RENGLONES_NIVELES IS
        SELECT
            LEVEL,
            ID,
            CODIGO_RENGLON,
            CODIGO_RENGLON_PADRE,
            NOMBRE
        FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES A
        WHERE A.ES_PADRE = 1
          AND A.ID_ORDEN_CAMBIO = VID_ORDEN_CAMBIO
          AND A.ID_CONTRATO = VID_CONTRATO
          AND LEVEL >= 2
          AND A.ORDEN = VORDEN
        START WITH A.CODIGO_RENGLON_PADRE IS NULL
        CONNECT BY PRIOR A.CODIGO_RENGLON = A.CODIGO_RENGLON_PADRE
        ORDER SIBLINGS BY ORDEN;

    CURSOR RENGLONES_NIVEL_ORDEN(P_CODIGO_PADRE VARCHAR2) IS
        SELECT
            LEVEL,
            ROW_NUMBER() OVER (ORDER BY ORDEN) NUMERO,
            ID,
            CODIGO_RENGLON,
            CODIGO_RENGLON_PADRE,
            NOMBRE
        FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES A
        WHERE A.ES_PADRE = 1
          AND A.ID_ORDEN_CAMBIO = VID_ORDEN_CAMBIO
          AND A.ID_CONTRATO = VID_CONTRATO
          AND A.CODIGO_RENGLON_PADRE = P_CODIGO_PADRE
          AND A.ORDEN = VORDEN
        START WITH A.CODIGO_RENGLON_PADRE IS NULL
        CONNECT BY PRIOR A.CODIGO_RENGLON = A.CODIGO_RENGLON_PADRE;


BEGIN
    /*Nivel #2*/
    FOR A IN RENGLONES_ORDENES LOOP
            FOR B IN RENGLONES_NIVEL_SEGUNDO LOOP
                    UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES SET
                        CODIGO_RENGLON= A.CODIGO_RENGLON || '.' || LPAD(B.NUMERO,2,'0')
                    WHERE ID= B.ID;
                    COMMIT;
                    UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES SET
                        CODIGO_RENGLON_PADRE= A.CODIGO_RENGLON || '.' || LPAD(B.NUMERO,2,'0')
                    WHERE  CODIGO_RENGLON_PADRE = B.CODIGO_RENGLON;
                    COMMIT;
                END LOOP;
        END LOOP;

    FOR C IN RENGLONES_NIVELES LOOP
            --DBMS_OUTPUT.PUT_LINE('Ingresado' || C.CODIGO_RENGLON);
            FOR D IN RENGLONES_NIVEL_ORDEN(C.CODIGO_RENGLON) LOOP
                    --DBMS_OUTPUT.PUT_LINE('VALOR CODIGO ' || C.CODIGO_RENGLON || ' NUMERO LINEA ' || D.NUMERO || ' NIVEL ' || C.LEVEL || ' d.renglon ' || D.CODIGO_RENGLON);
                    --DBMS_OUTPUT.PUT_LINE('Ingresado 2 ' || D.CODIGO_RENGLON);
                    UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES SET
                        CODIGO_RENGLON= C.CODIGO_RENGLON || '.' || LPAD(D.NUMERO,2,'0')
                    WHERE ID= D.ID;
                    COMMIT;
                    UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES SET
                        CODIGO_RENGLON_PADRE= C.CODIGO_RENGLON || '.' || LPAD(D.NUMERO,2,'0')
                    WHERE  CODIGO_RENGLON_PADRE = D.CODIGO_RENGLON;
                    COMMIT;
                END LOOP;
        END LOOP;

    DECLARE
        CURSOR C_RENGLONES IS
            SELECT
                ID,
                CODIGO_RENGLON
            FROM SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
            WHERE ID_ORDEN_CAMBIO = VID_ORDEN_CAMBIO
              AND ID_CONTRATO = VID_CONTRATO
              AND ES_PADRE = 1;
    BEGIN
        FOR R_RENGLONES IN C_RENGLONES
            LOOP
                UPDATE SAF.ORDENES_CAMBIO_RENGLONES_ACTIVIDADES
                SET ORDEN = TO_NUMBER(SUBSTR(R_RENGLONES.CODIGO_RENGLON, INSTR(R_RENGLONES.CODIGO_RENGLON, '.', -1) + 1))
                WHERE ID = R_RENGLONES.ID;
            END LOOP;
    END;
END;