CREATE OR REPLACE FUNCTION SAF.GET_CTA_BALANCE_RESULTADO
(
	V_CUENTA VARCHAR2,
    V_VERSION NUMBER
) 
RETURN VARCHAR2 AS
    CURSOR C_TIPO IS
        SELECT
            TIPCTA
        FROM SAF.CON_CATCTAS
        WHERE COD_CTA = V_CUENTA
        AND VERSION = V_VERSION;

    V_TIPCTA VARCHAR2(5);
BEGIN
    OPEN C_TIPO;
        FETCH C_TIPO INTO V_TIPCTA;
    CLOSE C_TIPO;

    RETURN V_TIPCTA;
END GET_CTA_BALANCE_RESULTADO;